### PR TITLE
Enhancements to lifecycle-setup classes.

### PR DESCRIPTION
**Pull request by isaki-x**
- Added constructors for executor service builders to allow specifying a
thread factory so that a thread factory is not built only to be thrown
away by a later call to the method to set the thread factory; the
ability to override the thread factory has not been removed for backward
compatibility.
- Exposed factory methods that create the builders based on already
existing thread factories, thus invoking the new constructors created in
the above comment.
- Issue #1563

### CODE REVIEW

**Comment by isaki-x** [comment]
#1563

**Comment by nickbabcock** [comment]
Looks like Travis is not happy with this PR.

**Comment by isaki-x** [comment]
Oddly enough Eclipse happily builds the original pull request and passes all the unit tests (I just double checked to make sure I hadn't overlooked an error). Regardless, I have pushed a fix.

**Comment by nickbabcock** [comment]
In the linked issue, it's mentioned that the current method:

> is [a] waste of time and resources

Can this be substantiated in any way. I realize that objectively it can be excessive but I'm not sure how tangible this benefit will be. This is more for my curiosity than anything

**Comment by joschi** [comment]
LGTM. :+1:

**Pull request merged**
