### PR TITLE
Simplify conditional expression

### PR DESCRIPTION
**Pull request by elifnurcevik**
Problem
The conditional expression is not easy to read.

Solution:
Simplify conditional expression

Result:
made it easier to read

This commitment supports to open source community for **Hacktoberfest**.

### CODE REVIEW

**Comment by jplock** [comment]
I think the way it was written had a clearer intent.

**Comment by elifnurcevik** [comment]
> I think the way it was written had a clearer intent.

The important thing is that anyone who does maintenance can easily read the code. Nobody can read intent.

**Comment by elifnurcevik** [comment]
Hi @joschi , @arteam what do you think about this pull request.

**Comment by joschi** [comment]
@elifnurcevik Thanks for your contribution.

I would agree with @jplock here that the original version was more straight forward to read.

**Pull request closed without merging**
