### PR TITLE
tomcat-jdbc and jdbi lib upgrades

### PR DESCRIPTION
**Pull request by profes**
versions:
tomcat-jdbc 8.0.24
jdbi 2.63

### CODE REVIEW

**Comment by joschi** [comment]
Could you please update the [release notes](https://github.com/dropwizard/dropwizard/blob/master/docs/source/about/release-notes.rst) as well?

**Comment by profes** [comment]
Done

**Comment by profes** [comment]
Travis build failed in some strange place. All tests pass on my machine. Can you rerun it on travis?

**Comment by arteam** [comment]
We probably should upgrade to JDBI 2.63.1 because 2.63 is not backward-compatible. See this [PR](https://github.com/jdbi/jdbi/pull/158).

**Comment by profes** [comment]
True. Fixed here https://github.com/dropwizard/dropwizard/pull/1194

**Pull request merged**
