### PR TITLE
Added httpCompliance to the HttpConnectorFactory

### PR DESCRIPTION
**Pull request by dren-dk**
Here's my shot at implementing the change discussed in issue 1824:
https://github.com/dropwizard/dropwizard/issues/1824

### CODE REVIEW

**Comment by arteam** [comment]
Looks good. A couple of requests:

* Could you please update `HttpConnectorFactoryTest`? We have 3 relevant tests for it (default configuration, full configuration, and a test for building a connector).
* Could please add this parameters to `HttpConnectorFactory`'s javadoc and the configuration [reference](https://github.com/dropwizard/dropwizard/blob/master/docs/source/manual/configuration.rst#http)? This should allow other users to know how to set the parameter and its purpose.

**Comment by dren-dk** [comment]
On it.

**Comment by dren-dk** [comment]
Ok, I have added test code and javadoc.

**Comment by arteam** [comment]
Thanks for your contribution!

**Pull request merged**
