### PR TITLE
Support disabled and enabled attributes for metrics

### PR DESCRIPTION
**Pull request by arteam**
Metrics 3.2.* allows to configure the set of attributes which can be disabled for a reporter. It would be nice to provide the ability to set them via the YAML config the same way we provide that for
metric names.

### CODE REVIEW

**Comment by jplock** [comment]
@arteam mind updating the release notes too?

**Comment by joschi** [comment]
@arteam Please update the documentation as well: https://github.com/dropwizard/dropwizard/blob/release/1.1.x/docs/source/manual/configuration.rst#metrics

**Comment by arteam** [comment]
Will do.

**Comment by arteam** [comment]
Thanks for fixing the markup!

**Pull request merged**
