### PR TITLE
Refactor testing of thrown exceptions

### PR DESCRIPTION
**Pull request by rhowe**
Simplify and normalise the test assertions relating to exceptions, favouring `assertThatExceptionOfType` over other mechanisms.

Sorry, it's quite big.

### CODE REVIEW

**Comment by rhowe** [comment]
Not sure what's going on with appveyor - the log seems truncated?

**Comment by arteam** [comment]
I've restarted the appveyor build, logs indeed seem to be truncated. Let's see if the error get reproduced.

**Comment by rhowe** [comment]
> I've restarted the appveyor build, logs indeed seem to be truncated. Let's see if the error get reproduced.

OK, thanks. I just rebased following the merge of the `dropwizard-client` part (I thought I'd have a go at just splitting this up into smaller PRs to see if it helped find a problem)

**Comment by arteam** [comment]
It looks like the Windows build fails on `FileAppenderFactoryTest`

```
[00:06:04] ERROR [2021-02-06 11:19:04,342] org.junit.jupiter.engine.execution.JupiterEngineExecutionContext: Caught exception while closing extension context: org.junit.jupiter.engine.descriptor.MethodExtensionContext@399655ce
[00:06:04] ! java.io.IOException: Failed to delete temp directory C:\Users\appveyor\AppData\Local\Temp\1\junit15593112168387161354. The following paths could not be deleted (see suppressed exceptions for details): , application.log
```

```
[00:06:04] ERROR [2021-02-06 11:19:04,342] org.junit.jupiter.engine.execution.JupiterEngineExecutionContext: Caught exception while closing extension context: org.junit.jupiter.engine.descriptor.MethodExtensionContext@399655ce
[00:06:04] ! java.io.IOException: Failed to delete temp directory C:\Users\appveyor\AppData\Local\Temp\1\junit15593112168387161354. The following paths could not be deleted (see suppressed exceptions for details): , application.log
[00:06:04] ! at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.createIOExceptionWithAttachedFailures(TempDirectory.java:262)
[00:06:04] ! at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:182)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[00:06:04] ! at org.junit.jupiter.engine.execution.ExtensionValuesStore.lambda$closeAllStoredCloseableValues$3(ExtensionValuesStore.java:68)
[00:06:04] ! at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[00:06:04] ! at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[00:06:04] ! at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
[00:06:04] ! at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
[00:06:04] ! at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
[00:06:04] ! at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
[00:06:04] ! at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[00:06:04] ! at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[00:06:04] ! at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[00:06:04] ! at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[00:06:04] ! at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[00:06:04] ! at org.junit.jupiter.engine.execution.ExtensionValuesStore.closeAllStoredCloseableValues(ExtensionValuesStore.java:68)
[00:06:04] ! at org.junit.jupiter.engine.descriptor.AbstractExtensionContext.close(AbstractExtensionContext.java:74)
[00:06:04] ! at org.junit.jupiter.engine.execution.JupiterEngineExecutionContext.close(JupiterEngineExecutionContext.java:53)
[00:06:04] ! at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.cleanUp(JupiterTestDescriptor.java:222)
[00:06:04] ! at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.cleanUp(TestMethodTestDescriptor.java:148)
[00:06:04] ! at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.cleanUp(TestMethodTestDescriptor.java:65)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$cleanUp$9(NodeTestTask.java:155)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.NodeTestTask.cleanUp(NodeTestTask.java:155)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:87)
[00:06:04] ! at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
[00:06:04] ! at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
[00:06:04] ! at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
[00:06:04] ! at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
[00:06:04] ! at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
[00:06:04] ! at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
[00:06:04] ! at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
[00:06:04] ! at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
[00:06:04] ! at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
[00:06:04] ! at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
[00:06:04] ! at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
[00:06:04] ! at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
[00:06:04] ! at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
[00:06:04] ! at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
[00:06:04] ! Suppressed: java.nio.file.DirectoryNotEmptyException: C:\Users\appveyor\AppData\Local\Temp\1\junit15593112168387161354
[00:06:04] ! 	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:267)
[00:06:04] ! 	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
[00:06:04] ! 	at java.base/java.nio.file.Files.delete(Files.java:1141)
[00:06:04] ! 	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.deleteAndContinue(TempDirectory.java:206)
[00:06:04] ! 	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:201)
[00:06:04] ! 	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:192)
[00:06:04] ! 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2742)
[00:06:04] ! 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
[00:06:04] ! 	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.deleteAllFilesAndDirectories(TempDirectory.java:192)
[00:06:04] ! 	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:180)
[00:06:04] ! 	... 57 common frames omitted
[00:06:04] ! Suppressed: java.nio.file.FileSystemException: C:\Users\appveyor\AppData\Local\Temp\1\junit15593112168387161354\application.log: The process cannot access the file because it is being used by another process.
[00:06:04] ! 
[00:06:04] ! 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[00:06:04] ! 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[00:06:04] ! 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[00:06:04] ! 	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:270)
[00:06:04] ! 	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
[00:06:04] ! 	at java.base/java.nio.file.Files.delete(Files.java:1141)
[00:06:04] ! 	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.deleteAndContinue(TempDirectory.java:206)
[00:06:04] ! 	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.visitFile(TempDirectory.java:196)
[00:06:04] ! 	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.visitFile(TempDirectory.java:192)
[00:06:04] ! 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2724)
[00:06:04] ! 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
[00:06:04] ! 	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.deleteAllFilesAndDirectories(TempDirectory.java:192)
[00:06:04] ! 	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:180)
[00:06:04] ! 	... 57 common frames omitted
[00:06:04] ! 	Suppressed: java.nio.file.FileSystemException: C:\Users\appveyor\AppData\Local\Temp\1\junit15593112168387161354\application.log: The process cannot access the file because it is being used by another process.
[00:06:04] ! 
[00:06:04] ! 		at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[00:06:04] ! 		at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[00:06:04] ! 		at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[00:06:04] ! 		at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:270)
[00:06:04] ! 		at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
[00:06:04] ! 		at java.base/java.nio.file.Files.delete(Files.java:1141)
[00:06:04] ! 		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.makeWritableAndTryToDeleteAgain(TempDirectory.java:224)
[00:06:04] ! 		at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.deleteAndContinue(TempDirectory.java:215)
[00:06:04] ! 		... 63 common frames omitted
```

**Comment by arteam** [comment]
Maybe `application.log` needs to be kept outside of the temporary directory, otherwise Windows doesn't allow it to be deleted.

**Comment by joschi** [comment]
We had a similar problem in https://github.com/dropwizard/dropwizard/issues/3677.

**Comment by rhowe** [comment]
> Maybe `application.log` needs to be kept outside of the temporary directory, otherwise Windows doesn't allow it to be deleted.

I guess the file's still held open and Windows is being Windows.

I'll split that one out for now and have a closer look at what the right thing to do is.

**Review by jplock — APPROVED** [review]

**Pull request merged**
