### PR TITLE
Add unit tests for io.dropwizard.util.Maps and Sets

### PR DESCRIPTION
**Pull request by petersear**
###### Problem:
I've analysed your code base and noticed that `io.dropwizard.util.Maps` and `io.dropwizard.util.Sets` are not fully tested.

###### Solution:
I've written some tests for the methods in these classes with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important in a subsequent PR.

### CODE REVIEW

**Comment by Sounie** [comment]
I don't see these tests adding muc value, particularly given the lack of meaning in their names.

**Comment by petersear** [comment]
@Sounie I'd be happy to try to improve names and other aspects of the tests if you have suggestions. I looked at names of existing tests before choosing these and went for <methodname><inputs> over <test><methodname> but agree they could be improved. In fact, it looks like I made a typo in the first test name - `ofd2KeyValuePairs()` should probably be `of2KeyValuePairs()`

**Comment by StephenSouness** [comment]
Out of curiosity, why are you pushing "Diffblue" in so many repositories that you do not appear to have made any earlier commits to?

It could be construed as spam.

Do you have an interest to declare?

**Comment by joschi** [comment]
@petersear Thanks for your contribution!

Could you please fix the typo in the test method you've mentioned?
Then we'll merge the PR.

**Comment by whitfin** [comment]
@StephenSouness it's already declared in their public GitHub profile; they're under that org :p

**Comment by StephenSouness** [comment]
Ah, now I see.

Apologies if I came across as cynical.  Was wondering if there was some reason for the PR not having feedback.  2 + 2 => 5

**Comment by petersear** [comment]
@whitfin thanks
@Sounie NP
@joschi I have fixed the typo in the test name and pushed the branch again.

**Pull request merged**
