### PR TITLE
Support  `@UnitOfWork` outside of Jersey resources

### PR DESCRIPTION
**Pull request by arteam**
This PR provides the ability to use the `@UnitOfWork` annotation outside of Jersey resources.
It consists from two changes: 
* In first we move operations over `@UnitOfWork` methods from `UnitOfWorkApplicationListener` into  an aspect. It allows to perform these operations outside of the listener (for example, in proxies or AOP providers).
* In second we provide a factory for creating `@UnitOfWork` aware proxies. A created proxy will
detect the annotation on component methods and will open/close a Hibernate session around them.
It uses aforementioned aspect for this. Javassist is used for creating proxies, because it has a
simple API for that and it's shipped with Hibernate.

Now to use `@UnitOfWork` in authenticators, one need just to create proxy like this:
```java
SessionDao dao = new SessionDao(hibernateBundle.getSessionFactory());
ExampleAuthenticator exampleAuthenticator = 
                new UnitOfWorkAwareProxyFactory(hibernateBundle)
                .create(ExampleAuthenticator.class, SessionDao.class, dao);
```

This change is intended to 0.9.* branch. Reference issues: #1334 , #1240

### CODE REVIEW

**Comment by jplock** [comment]
Personally I don't have any way to test this change even though there's been a lot of chatter about it.  Does anyone else have a way to validate this and/or merge it in?

**Comment by arteam** [comment]
A simple way to test this is to try to use `@UnitOfWork` with Hibernate sessions in authenticators. Authentification is now performed outside of Jersey lifecycle for security reasons, so the process should fail without a proxy.

**Comment by jplock** [comment]
@harshil07, @paukiatwee, @dotCipher, @yiweig, @vvondra can anyone confirm if this PR resolves your issue?

**Comment by harshil07** [comment]
Happy to test @jplock but I'm not entirely sure on how to build the module for java 8.

**Comment by arteam** [comment]
This PR is against the 0.9 branch, which still uses Java 7. Something like this should work, though.

```bash
git checkout -b arteam-generalize_unit_of_work release/0.9.x
git pull https://github.com/arteam/dropwizard.git generalize_unit_of_work
cd ./dropwizard-bom
mvn install
cd ../
mvn install -DskipTests=true -p dev
```

**Comment by vvondra** [comment]
@jplock In the end, since I use dropwizard-guice, I went with a simple proxy using https://github.com/google/guice/wiki/AOP or I actually inject a TransactionProvider class which has a method I can pass a callback to which will be executed transactionally

**Comment by paukiatwee** [comment]
I tested this PR and it is working! Passed all my tests.

**Set up**
```
TokenAuthenticator tokenAuthenticator = new UnitOfWorkAwareProxyFactory(hibernate).create(TokenAuthenticator.class, FinanceService.class, financeService);
// auth
final OAuthCredentialAuthFilter<User> authFilter =
        new OAuthCredentialAuthFilter.Builder<User>()
                .setAuthenticator(tokenAuthenticator)
                .setPrefix("Bearer")
                .setAuthorizer(new DefaultAuthorizer())
                .setUnauthorizedHandler(new DefaultUnauthorizedHandler())
                .buildAuthFilter();
```

**Authenticator**
```
public class TokenAuthenticator implements Authenticator<String, User> {

    private final FinanceService financeService;

    public TokenAuthenticator(FinanceService financeService) {
        this.financeService = financeService;
    }

    @UnitOfWork
    @Override
    public Optional<User> authenticate(String token) throws AuthenticationException {
        java.util.Optional<User> option = financeService.findUserByToken(token);
        if(option.isPresent()) {
            return Optional.of(option.get());
        } else {
            return Optional.absent();
        }
    }
}
```

Previously `financeService.findUserByToken(token)` will throw error.

**Comment by jplock** [comment]
Excellent!  Thank you for confirming @paukiatwee.

**Comment by jplock** [comment]
@arteam are you going to cherry pick this into `master` as well for 1.0.0?

**Comment by arteam** [comment]
Yes, will do.

**Comment by arteam** [comment]
Commits 39a857d and 0a5534e are cherry-picked to the master branch.

**Comment by arteam** [comment]
@dropwizard/committers, what do you think about releasing 0.9.2 with this workaround?

**Comment by jplock** [comment]
+1 from me

**Comment by shashank261** [comment]
+1

Thanks & Regards
Shashank Harwalkar

**Comment by kkamkou** [comment]
+1

**Pull request merged**
