### PR TITLE
Upgrade to Dropwizard Metrics 3.2.0

### PR DESCRIPTION
**Pull request by arteam**
http://metrics.dropwizard.io/3.2.0/about/release-notes.html

### CODE REVIEW

**Comment by jplock** [comment]
@dropwizard/committers should we cherry-pick this into `release/1.1.x`, or update 1.1.0 with metrics `3.1.3`?  Any thoughts?  Personally I'd probably prefer `3.2.0` as it has been awhile since a new metrics release.

**Comment by evnm** [comment]
I vote for including this change in 1.1.0, provided we can get it into a release candidate or two in order to kick the tires.

**Comment by arteam** [comment]
One of nice features of the 3.2.0 release is the ability to disable some metric attributes from being reported. We can provide the YAML configuration of such attributes the same way we filter metric names.

**Comment by jplock** [comment]
Cherry picked into `release/1.1.x` in https://github.com/dropwizard/dropwizard/commit/676c9ebbbd7785ce57e98be7e685ae8517804407 and added release notes in https://github.com/dropwizard/dropwizard/commit/a61abef87097acc68733444b32f9af4e04fdfde4

**Comment by jplock** [comment]
We should probably create an rc2 soonish :)

**Pull request merged**
