### PR TITLE
Dependency reorganization

### PR DESCRIPTION
**Pull request by joschi**
The purpose of this PR are threefold:

* *Create properties for all dependencies*:
Allow overriding the version of every dependency of Dropwizard by setting a Maven property
* *Split BOM into Dropwizard modules and dependencies*:
The bill of materials for all Dropwizard dependendencies is now named `io.dropwizard:dropwizard-dependencies` and `io.dropwizard:dropwizard-bom` manages the version of all Dropwizard modules, but no other dependencies (refs #2880)
* *Introduce dropwizard-project for common build configuration*:
`io.dropwizard:dropwizard-parent` is still the parent POM for most Dropwizard modules, but automatically includes the dependencies from `io.dropwizard:dropwizard-bom` and `io.dropwizard:dropwizard-dependencies`. The `io.dropwizard:docs` module inherits from `io.dropwizard:dropwizard-project` but doesn't have any overlap with any of the Dropwizard modules carrying code.

TODO:

* [ ] Document changes with regards to `io.dropwizard:dropwizard-bom` in the Dropwizard 2.0.x migration guide

### CODE REVIEW

**Comment by joschi** [comment]
@dropwizard/core Any thoughts on this PR?

This would be the last change I want to bring in before releasing Dropwizard 2.0.0.

**Comment by jplock** [comment]
:shipit: 🎉

**Comment by joschi** [comment]
> Shame that it'll be a breaking change for everyone

@nickbabcock I thought about naming the bill of materials differently, i. e. "dropwizard-bom-modules" and keeping "dropwizard-bom" the way it was before.

This would be an option which retains backward-compatibility, but we'll have to come up with a *good* name for the BOM referring to only the Dropwizard modules.

Any suggestions?

**Comment by nickbabcock** [comment]
IMO it's fine in lieu of a better name, and 2.0 is as good as a time we'll get for this breaking change.

**Pull request merged**
