### PR TITLE
Fix NullPointerException in DropwizardApacheConnector

### LINKED ISSUE #7319: Content-Encoding header is null but not expected
`DropwizardApacheConnector` has the private class BufferedJerseyRequestHttpEntity that expects a `Content-Encoding` header that is not suppose to be mandatory.

### PR DESCRIPTION
**Pull request by Mahoney**
###### Problem:
If `JerseyClientConfiguration.setGzipEnabledForRequests(false)` then there is no `CONTENT_ENCODING` header
on the `org.glassfish.jersey.client.ClientRequest`.

`org.glassfish.jersey.client.ClientRequest` returns null from `getRequestHeader` if there is no header, which causes
this code to fail.

###### Solution:
Check for null and handle it correctly

Fixes #7319

### CODE REVIEW

**Comment by Mahoney** [comment]
Don't have time to write a failing test right now, might be able to come back to it in a few days.

**Review by zUniQueX — CHANGES_REQUESTED** [review]
@Mahoney The change looks good. But the behavior is now inconsistent between the buffered and the chunked entity. Could you extract the new method to the enclosing class and call it in the buffered entity too?

**Comment by Mahoney** [comment]
@zUniQueX updated with the requested change

**Review by zUniQueX — APPROVED** [review]
Thanks, LGTM!

**Comment by Mahoney** [comment]
What further needs to happen to get this merged?

**Comment by zUniQueX** [comment]
@Mahoney We currently investigate some infrastructure issues. This PR will probably be merged afterwards.

**Comment by joschi** [comment]
@Mahoney Thanks a lot for your contribution! ❤️

**Pull request merged**
