### PR TITLE
Upgrade logback (fixes #1699)

### LINKED ISSUE #1699: Broken query parameter extraction in POST requests
See post-closure comments on #1606.

### PR DESCRIPTION
**Pull request by markelliot**

### CODE REVIEW

**Comment by markelliot** [comment]
logback 1.1.10 includes the following fix:

> The AccessEvent.prepareForDeferredProcessing() method was not idempotent. This caused subtle bugs under Jetty. See LOGBACK-1189 for details.

**Comment by jplock** [comment]
Thanks!

**Comment by vrolijken** [comment]
Just curious, any reason not to update to the latest greatest (1.2.1)?

**Comment by markelliot** [comment]
I took latest at the time, probably makes sense to go further.

**Comment by jplock** [comment]
https://github.com/dropwizard/dropwizard/pull/1927 was merged in yesterday to `master` and `release/1.1.x`

**Pull request merged**
