### PR TITLE
Register the default MetricRegistry as the "default"

### PR DESCRIPTION
**Pull request by jplock**
I end up doing this a lot in my code so I can reference the `MetricRegistry` throughout my app.

### CODE REVIEW

**Comment by mattnelson** [comment]
I've done this many times as well, but also tried to add first class default support to the metrics registry. I wasn't fond of having to rely on a magic string for the default registry.

https://github.com/dropwizard/metrics/pull/849

**Comment by jplock** [comment]
Good call. Let's see where that can go.

**Comment by jplock** [comment]
Is there any harm in merging this pull request and then refactoring whenever we can upgrade the metrics library?

**Comment by joschi** [comment]
@jplock Nope, it's fine I think. :+1:

**Comment by jplock** [comment]
thanks!

**Comment by erikvanoosten** [comment]
Will the same be done for the health check registry in `SharedHealthCheckRegistries`?

**Comment by joschi** [comment]
@erikvanoosten Good catch. I've addressed this in #1722.

**Pull request merged**
