### PR TITLE
Upgrade to Jersey 2.20

### PR DESCRIPTION
**Pull request by tjcutajar**

### CODE REVIEW

**Comment by jplock** [comment]
Merge conflicts

**Comment by joschi** [comment]
What are the changes in Jersey 2.20? https://jersey.java.net/release-notes/ doesn't list the release notes for that version yet…

**Comment by tjcutajar** [comment]
See https://java.net/jira/secure/ReleaseNote.jspa?projectId=10014&version=17325

**Comment by joschi** [comment]
LGTM. Thanks!

**Pull request merged**
