### PR TITLE
Remove Dropwizard's Jackson dependency on Logback

### PR DESCRIPTION
**Pull request by arteam**
In the move to allow users plug in custom logging implementations except Logback, we should make all Logback dependencies in Dropwizard optional. Currently, our Jackson mapper is dependent on Logback for
deserializing logging `Level` in the configuration. It's forces every Dropwizard app to have a runtime dependency on Logback. To avoid this we could remove `Level` deserializers and move converting a string text level to Logback's level to `DefaultLoggingFactory`. Since `DefaultLoggingFactory` can be replaced by `ÈxternalLoggingFactory` this allows users to run Dropwizard app without a Logback dependency.

### CODE REVIEW

**Comment by arteam** [comment]
Ah, I forgot about `threshold` in `AbstractAppenderFactory`, but we can't change its type because it's `protected` and part of the public API.

**Comment by jplock** [comment]
@arteam this good to merge?

**Comment by arteam** [comment]
I guess this should be good to merge. The issue was reported by @jsauvain in #1900 and the change in the pull requests should fix it. My biggest concert is that we have to change the public API which could break third-party appenders. I had a look at them and most of them use `threshold` variable directly or don't use at all. 

I am leaning to merge this MR and cut a release candidate. In case this change breaks something important, we can revert it.

**Comment by swagle** [comment]
This change is missing in the 1.2.x line. Hit this issue when trying to use this feature on 1.2.0 bits published to maven central.

**Comment by joschi** [comment]
@swagle Nope, the commit (c28ca30d400bf50a9b93209a7887a20b68a4c209) is also part of Dropwizard 1.2.0.

**Comment by swagle** [comment]
Hi @joschi, you are right the patch is present, this breaks at io.dropwizard.Application#bootstrapLogLevel

**Comment by arteam** [comment]
For those who experience this issue, you should override `bootstrapLogging()` and then `bootstrapLogLevel(Level)` won't be invoked.

```java
public class ExampleApplication extends Application<ExampleConfiguration> {

    @Override
    protected void bootstrapLogging() {
    }

    @Override
    public void run(ExampleConfiguration exampleConfiguration, Environment environment) throws Exception {
        LoggerFactory.getLogger(ExampleApplication.class).info("Test: {}", exampleConfiguration.getTest());
    }

    public static void main(String[] args) throws Exception {
        new ExampleApplication().run(args);
    }
}
```

**Comment by jdimeo** [comment]
I must be missing something because I just pulled down 1.2.0 from Maven Central today in eager anticipation of this PR, and the source code for Application.java has `import ch.qos.logback.classic.Level;` and APIs that reference `Level` thus triggering indirect class not found compilation errors when I try to use Log4j. 
The SHA1 of the sources.jar I pulled down for core is `2c35bff8aeb55631cfd21cbe9c021c4d60b9e4df`

**Comment by arteam** [comment]
Yes, the import is still there, but the JVM lazily initializes classes and methods lazily, so if you override the `bootstrapLogging` method in the `Application` class (which invokes the `bootstrapLogLevel` method=, your application should successfully load. 

I created a simple demo for a Dropwizard app with log4j 2: https://github.com/arteam/dropwizard-nologback

**Comment by jdimeo** [comment]
So, to be more precise, you are correct in that I can get a clean compile with `javac` (specifically `mvn clean compile`). However, my IDE (specifically Eclipse) is fooled (or too smart for its own good, depending on how you look at it). See:
image
That prevents me from running my service through the IDE.

Thank you for the demo app! A skeleton app is worth a thousand words.

**Comment by rvsasseen** [comment]
I found that there are further magic incantations needed which are described at https://www.dropwizard.io/1.3.5/docs/manual/core.html#logging.

**Pull request merged**
