### PR TITLE
Upgrade to logback 1.2.1

### PR DESCRIPTION
**Pull request by tjcutajar**

### CODE REVIEW

**Comment by jplock** [comment]
Are there any breaking changes or other items to be aware of as part of this upgrade?

**Comment by tjcutajar** [comment]
There isn't any impact of the API change to `ch.qos.logback.core.encoder.Encoder` as far as I can see.

Notes: https://logback.qos.ch/news.html

**Comment by jplock** [comment]
@dropwizard/committers should we merge this in and get it into 1.1.0?  Thoughts?

**Comment by evnm** [comment]
The lock-granularity improvement is enticing. I'd vote for including it in 1.1.0, unless any issues crop up in the release candidates.

**Comment by jplock** [comment]
I'll merge it into master at least.

**Comment by jplock** [comment]
Cherry-picked into `release/1.1.x` in https://github.com/dropwizard/dropwizard/commit/f1d0402b71bc1b01f38397ae5a340635f82b7daf

**Pull request merged**
