### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by joschi**
Assorted dependency updates.

### CODE REVIEW

**Comment by arteam** [comment]
The change looks good to me, but it looks like that the latest Jersey update broke some unit tests for the Jersey module. It looks like the build at Travis was killed because a test took too much time to complete.

**Comment by joschi** [comment]
@arteam Looks like Jetty and Errorprone currently cause some problems. I've removed these commits from this PR to take a look at them separately.

**Comment by arteam** [comment]
Crap, looks like the build failed after the merge. I've restarted it several times, but without success. Some Jersey test never completes in a timely manner and Travis kills a test suite.

**Comment by joschi** [comment]
@arteam The build has passed now. No idea why Travis CI keeps failing from time to time.

Maybe we should take a look at alternatives if this keeps happening.

**Comment by mattnelson** [comment]
Discovered the non-passive changes in logback-1.1.8 today, when we were upgrading all of our transitive dependencies. Glad to see it has already been addressed in dropwizard. Are there plans to either patch back the logback changes to 1.0.X or release 1.1.0?

**Comment by joschi** [comment]
@mattnelson We're aiming to publish the first release candidate of Dropwizard 1.1.0 within January.

Backporting this change to Dropwizard 1.0.x will most likely not happen.

**Pull request merged**
