### PR TITLE
Add DataSourceFactory.rollbackOnReturn flag

### PR DESCRIPTION
**Pull request by patrox**
Resolves: #1488

### CODE REVIEW

**Comment by jplock** [comment]
I think we need a setter in the DataSourceFactory. Otherwise looks good. Is this enabled or disabled by default today?

**Comment by jplock** [comment]
Do you also need to add it when the pool is built?

**Comment by patrox** [comment]
It's disabled by default, just like `DataSourceFactory.commitOnReturn`

**Comment by patrox** [comment]
> Do you also need to add it when the pool is built?

yes, I missed that - fixed

**Comment by joschi** [comment]
@patrox Please avoid mere whitespace changes in `docs/source/manual/configuration.rst`. Other than that the changes look good to me.

**Comment by patrox** [comment]
@joschi Sorry for that - I guess that IDEA reformatted code during save - should I revert these changes ?

**Comment by joschi** [comment]
@patrox It seems to be caused by our current [`.editorconfig`](https://github.com/dropwizard/dropwizard/blob/master/.editorconfig) file. Just keep it that way.

**Comment by joschi** [comment]
Thanks!

**Pull request merged**
