### PR TITLE
metrics version 3.1.4

### PR DESCRIPTION
**Pull request by osigida**
Metrics 3.1.3 and 3.1.4 contains some bug fixes, with are quite useful.

### CODE REVIEW

**Comment by arteam** [comment]
Good idea. I think the Graphite and ThreadLocal bugs are quite big to warrant a new maintenance release for Dropwizard. Thanks for contributing!

**Comment by arteam** [comment]
I will wait a little bit, and if nobody raises any objection will release Dropwizard 1.0.7 tonight.

**Comment by osigida** [comment]
@arteam 👍

**Comment by arteam** [comment]
Dropwizard 1.0.7 has been released to the Maven central repository.

**Comment by arteam** [comment]
For anyone wondering to update or not, here are the release notes for Metrics 3.1.3 and 3.1.4

* http://metrics.dropwizard.io/3.2.2/about/release-notes.html#v3-1-3-feb-24-2017
* http://metrics.dropwizard.io/3.2.2/about/release-notes.html#v3-1-4-mar-10-2017

**Comment by osigida** [comment]
@arteam, I'm trying to use version 1.0.7 which was released yesterday, but it looks like something went wrong at the upload to maven and some of the artifacts are not there.

At the moment I miss https://search.maven.org/remotecontent?filepath=io/dropwizard/dropwizard-jersey/1.0.7/dropwizard-jersey-1.0.7.jar 
Maybe there are more.

Could you please check?
Thanks a lot in advance

**Comment by arteam** [comment]
It looks like the search index got corrupted during uploading to the Maven central. I've checked a md5 checksum for the artefact at http://repo1.maven.org/maven2/io/dropwizard/dropwizard-jersey/1.0.7/dropwizard-jersey-1.0.7.jar.md5 and it's the same with the checksum from `dropwizard-jersey-1.0.7.jar` in my local repository. I will create a ticket in the Sonatype JIRA, hopefully they will help.

**Comment by arteam** [comment]
https://issues.sonatype.org/browse/OSSRH-29004

**Comment by t-tsutsumi** [comment]
@joschi FYI, the v1.1.0 seems to be corrupted as well. :-(
* http://repo.maven.apache.org/maven2/io/dropwizard/dropwizard-servlets/1.1.0/dropwizard-servlets-1.1.0.jar

**Comment by arteam** [comment]
Sonatype responded in the ticket. They purged caches and now dropwizard-jersey 1.0.7 should be accessible in builds. dropwizard-servlets-1.1.0 still unavailable, though.

**Comment by arteam** [comment]
It looks like Sonatype resolved this issue as well and the 1.1.0 artefacts should available too.

**Comment by t-tsutsumi** [comment]
@arteam Unfortunately, http://repo.maven.apache.org/maven2/io/dropwizard/dropwizard-views/1.0.7/dropwizard-views-1.0.7.jar still unavailable.

**Comment by arteam** [comment]
Ah, that's very unfortunate. We will need to reopen the ticket again.

**Comment by arteam** [comment]
It should be fixed now.

**Comment by t-tsutsumi** [comment]
It seems to be working. thanks!

**Pull request merged**
