### PR TITLE
bugfix - getting started doc

### PR DESCRIPTION
**Pull request by codebuff**
sayHello
    @QueryParam("name") doesn't identify Optional<String>
  alternate implementation exists at /example/helloworld/core/Template.java

### CODE REVIEW

**Comment by nickbabcock** [comment]
Wait, what's the bugfix? :confused:

**Comment by codebuff** [comment]
I tried to follow the [tutorial](http://www.dropwizard.io/1.0.0/docs/getting-started.html) .
It compiled fine (mvn package), however it didn't run. (... server hello-world.yml)
This commits makes changes to getting started doc to address the issue.

Please note that:
The code in example repo is different than that of getting started doc, which doesn't have this issue, but that would require creation of one more file (in getting started tutorial), this commits avoid that by changing two lines in method sayHello)

**Comment by nickbabcock** [comment]
The getting started should be fine. What dropwizard version are you using?

**Comment by codebuff** [comment]
dropwizard version 0.9.1, project created from archetype (as per tutorial)
Optional of Java8 (Guave doesn't include orElse)

**Comment by nickbabcock** [comment]
Ah yeah, looks like you were using Dropwizard 0.9.x with the 1.0 getting started. Try following [0.9.x getting started](http://www.dropwizard.io/0.9.0/docs/getting-started.html), or upgrade to 1.0

**Pull request closed without merging**
