### PR TITLE
Syntax error in docs scrubbed, and MultiPartBundle includes config interface now

### PR DESCRIPTION
**Pull request by pavangupta**
Configuration interface is now carried into the MultiPartForm bundle and I grabbed a quick syntax error in the docs.  Everything should match up.

### CODE REVIEW

**Comment by joschi** [comment]
Please open two separate pull requests for those issues.

Your change also doesn't pass the test suite.

**Comment by joschi** [comment]
Why would `MultiPartBundle` need a `Configuration` instance?

Closing this PR (the typo in the docs has been addressed in a separate commit).

**Comment by pavangupta** [comment]
Totally agreed on the ``Configuration`` not making sense as a requirement, but I guessed the docs had some reason I couldn't see.  To be clear, the docs are still suggesting an illegal inclusion of ``ExampleConfiguration`` in the ``MultiPartBundle`` declaration.

**Comment by joschi** [comment]
@pavangupta Hah, you're right. The docs are wrong in this case. Thanks for mentioning it!

**Comment by pavangupta** [comment]
@joschi woot, happy to help!

**Pull request closed without merging**
