### PR TITLE
Verbose logging of server errors

### PR DESCRIPTION
**Pull request by maffe**

### CODE REVIEW

**Comment by jplock** [comment]
Does anyone @dropwizard/committers know why we weren't logging these errors to begin with?

**Comment by nickbabcock** [comment]
Accidental side effect of #1193?

**Comment by jplock** [comment]
Is there any benefit to only logging server errors or should we just log every exception?

**Comment by nickbabcock** [comment]
Ah, sorry, I misspoke before. `WebApplicationException` was never logged when mapped by `LoggingExceptionMapper`, and I can see why this may have been an oversight. I think generally internal server errors arise from unexpected exceptions. I'm not sure under what circumstances I would write:

```java
throw new WebApplicationException("KAPOW", Response.Status.INTERNAL_SERVER_ERROR);
```

@maffe, can you give an situation?

**Comment by maffe** [comment]
@nickbabcock Such exceptions happen when the model has invalid annotations, for example:
```java
@XmlRootElement
public class Customer {
  private Integer customerNumber;

  @XmlID // can only be used on strings
  public Integer getCustomerNumber() {
    return customerNumber;
  }
  
  public void setCustomerNumber(final Integer customerNumber) {
    this.customerNumber = customerNumber;
  }
}
```

Log entry (with the proposed extended logging):
```
ERROR [2015-10-15 13:37:47,615] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 284fe2ebbaa1a788
! com.sun.xml.internal.bind.v2.runtime.IllegalAnnotationsException: 1 counts of IllegalAnnotationExceptions
! at com.sun.xml.internal.bind.v2.runtime.IllegalAnnotationsException$Builder.check(IllegalAnnotationsException.java:91) ~[na:1.8.0_60]
! at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:445) ~[na:1.8.0_60]
! at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:277) ~[na:1.8.0_60]
! at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:124) ~[na:1.8.0_60]
! at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1123) ~[na:1.8.0_60]
! at com.sun.xml.internal.bind.v2.ContextFactory.createContext(ContextFactory.java:147) ~[na:1.8.0_60]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
! at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
! at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:247) ~[na:1.8.0_60]
! at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:234) ~[na:1.8.0_60]
! at javax.xml.bind.ContextFinder.find(ContextFinder.java:462) ~[na:1.8.0_60]
! at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:641) ~[na:1.8.0_60]
! at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:584) ~[na:1.8.0_60]
! at org.glassfish.jersey.jaxb.internal.AbstractJaxbProvider.getStoredJaxbContext(AbstractJaxbProvider.java:311) ~[iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.jaxb.internal.AbstractJaxbProvider.getJAXBContext(AbstractJaxbProvider.java:296) ~[iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.jaxb.internal.AbstractJaxbProvider.getMarshaller(AbstractJaxbProvider.java:263) ~[iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.jaxb.internal.AbstractJaxbProvider.getMarshaller(AbstractJaxbProvider.java:230) ~[iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.jaxb.internal.AbstractCollectionJaxbProvider.writeTo(AbstractCollectionJaxbProvider.java:266) ~[iphvp-webservice-1.0-SNAPSHOT.jar:na]
! ... 55 common frames omitted
! Causing: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
! at org.glassfish.jersey.jaxb.internal.AbstractCollectionJaxbProvider.writeTo(AbstractCollectionJaxbProvider.java:274) ~[iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:265) ~[iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250) ~[iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162) ~[iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:106) ~[iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162) ~[iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:86) ~[iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162) ~[iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1130) ~[iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:683) ~[iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:424) ~[iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:414) ~[iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:312) ~[iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:292) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1139) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:460) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at io.dropwizard.jetty.BiDiGzipFilter.doFilter(BiDiGzipFilter.java:134) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:29) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:44) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.eclipse.jetty.server.Server.handle(Server.java:497) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [iphvp-webservice-1.0-SNAPSHOT.jar:na]
! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
0:0:0:0:0:0:0:1 - - [15/Okt/2015:13:37:47 +0000] "GET /customer HTTP/1.1" 500 316 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0" 421
```
Instead of evaluating the Response.Status.Family, one could check if the exception is a `javax.ws.rs.ServerErrorException` (which extends `WebApplicationException`).

**Comment by nickbabcock** [comment]
Interesting, I did not consider `ServerErrorException`. Thank you, maffe, for pointing that out. As an aside, I wonder under what circumstances that exception is generated because I'm not familiar with it.

@jplock I don't believe there is a benefit to only logging internal server errors (other than reducing log spam). Personally, I'd be fine for logging of other exceptions (but not under the error level and not with stacktraces).

**Comment by jplock** [comment]
This looks good to me if you'd like to merge it in.  Thanks for the contribution @maffe

**Comment by joschi** [comment]
LGTM.

@maffe Thanks for your contribution.

**Pull request merged**
