### PR TITLE
Upgrade to JDBI 2.70

### PR DESCRIPTION
**Pull request by arteam**
A pretty big JDBI upgrade. See the release announcement [here](https://groups.google.com/forum/#!topic/jdbi/onYQtaBeEng).

### CODE REVIEW

**Comment by jplock** [comment]
Sounds great, thanks!

**Comment by jplock** [comment]
Do you want to update the release notes as well?

**Comment by arteam** [comment]
> Do you want to update the release notes as well?

Done

**Comment by joschi** [comment]
"A pretty big JDBI upgrade" and only 1 line changed in our POM. I love those kind of updates. :wink:

**Pull request merged**
