### PR TITLE
Cache maven repository in travis

### PR DESCRIPTION
**Pull request by jplock**

### CODE REVIEW

**Comment by joschi** [comment]
Caching between builds is currently only available on the paid subscriptions for Travis CI: http://docs.travis-ci.com/user/caching/

**Comment by jplock** [comment]
It says it supports their new container-based architecture (http://docs.travis-ci.com/user/workers/container-based-infrastructure/), which I think we're using:

```
This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
If you require sudo, add 'sudo: required' to your .travis.yml
See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.
```

**Comment by joschi** [comment]
Yes, running on the new infrastructure for their paying customers (travis-ci.com feature). :wink:

I mean we can still add it, but it doesn't have any effects on our builds running on travis-ci.org.

**Comment by jplock** [comment]
I'm doing this on a personal project and it seems to be using the cache.  I honestly have no idea, but it seems to be working even though I'm not paying for it.  :)

**Comment by carlo-rtr** [comment]
Let's give it a whirl!

**Comment by joschi** [comment]
I stand corrected: https://travis-ci.org/dropwizard/dropwizard/jobs/70786272#L94

It seems to work. Thanks, Justin! :smile:

**Comment by nickbabcock** [comment]
What are the benefits? I initially thought that it would cut down build times but according to the [builds](https://travis-ci.org/dropwizard/dropwizard/builds), it doesn't look to be the case (builds are still taking ~50-55 minutes total).

**Comment by jplock** [comment]
I think we just need to watch it in a future PR to see if it's being used.  Carlo's most recent PR didn't download anything due to the cache so it has to be showing some improvement.

**Comment by joschi** [comment]
https://travis-ci.org/dropwizard/dropwizard/caches is showing some data in the Travis CI caches.

**Pull request merged**
