### PR TITLE
Provide dependency injection for auth filter objects

### PR DESCRIPTION
**Pull request by zUniQueX**
Raised for consideration regarding issue #4238.

### CODE REVIEW

**Review by joschi — APPROVED** [review]
LGTM. Thanks! 😄

**Comment by pstackle** [comment]
@zUniQueX Sorry that I didn't get a chance to review this sooner, but I just tried out v2.1.0-beta.8 and this change broke the ability to use dropwizard-auth's DynamicAuthFeature with a non-AuthFilter-based ContainerRequestFilter.

Was that intended?

Looking closer at this change, I'm not sure it is necessary to end up wrapping the user-provided ContainerRequestFilter with another ContainerRequestFilter (InjectingFilter). 

Instead, you should be able to do the injection within the AuthDynamicFeature class before registering the auth filter instance. For example, in the `registerAuthFilter()`  method, you could call `injectionManager.inject(authFilter)` just before calling `context.register(authFilter)` and that should end up populating that instance with the necessary jersey proxy class that will then populate a `@Context HttpServletRequest httpRequest` field with the correct value on each request.

**Comment by zUniQueX** [comment]
> Instead, you should be able to do the injection within the AuthDynamicFeature class before registering the auth filter instance. For example, in the `registerAuthFilter()`  method, you could call `injectionManager.inject(authFilter)` just before calling `context.register(authFilter)` and that should end up populating that instance with the necessary jersey proxy class that will then populate a `@Context HttpServletRequest httpRequest` field with the correct value on each request. 

@pstackle I'm not sure, if this would work. We cannot create a proxy of the user defined auth filter ourselves (the user can define own constructors) and therefore we cannot handle the injection within a proxy.

The `DynamicFeature` configuration process is done once at application startup, so we would be only injecting once into the object. I'm not sure this really is what we want. Or is it enough for every injected object that it's done once to return the current value on every access? Therefore I'm not deep enough into HK2.

We could modify the `InjectingFilter` to inject into those filters too, but to skip the injection into `Authenticator` and `Authorizer` instances. Then we don't have to throw an exception there.

**Comment by zUniQueX** [comment]
@pstackle I looked into the Jersey docs, but I can't find something on the topic when and how often manual DI should be done.

I think the `InjectingFilter` would however provide more guarantees. If we use your approach to do the DI once at configuration of the `DynamicFeature` and the user would however set an injected object to `null`, the object won't get injected on the next request. When using the `InjectingFilter`, a user would get a valid object in this situation.

I can't imagine a case where this is relevant at the moment, but if we can provide this degree of freedom, I think we shouldn't take it out. As both approaches (nearly) do the same things, I would leave the code as-is for now, but I don't have an other good reason for that. If you have more experience with HK2 and this would give us a benefit, I'm happy to raise a PR for that.

**Comment by pstackle** [comment]
@zUniQueX Thanks for digging into this. I know that the Jersey DI stuff is pretty complicated and I usually end up struggling quite a bit with it myself. But, luckily I've done this exact thing before and it works correctly. Since I don't expect you to just take my word for it, I've created the following pull request that showcases the behavior I was describing and adds a couple tests that proves that the injected values are in fact updated with the per-request values. 

PR: https://github.com/dropwizard/dropwizard/pull/5197

> If we use your approach to do the DI once at configuration of the DynamicFeature and the user would however set an injected object to null, the object won't get injected on the next request. 

What is the use case you are thinking of where the user would set an injected field value to null? I think that statement would apply for any DI behavior and I'm not sure it makes sense for us to try and defend against that. By doing the DI setup once, during startup, we avoid completely the overhead of the redundant injection on every request. Given the amount of reflection that is used in HK2's injection code, I'd imagine this is a costly operation and I would not want to start incurring that overhead inline with every authenticated request.

**Comment by zUniQueX** [comment]
> What is the use case you are thinking of where the user would set an injected field value to null? I think that statement would apply for any DI behavior and I'm not sure it makes sense for us to try and defend against that. By doing the DI setup once, during startup, we avoid completely the overhead of the redundant injection on every request. Given the amount of reflection that is used in HK2's injection code, I'd imagine this is a costly operation and I would not want to start incurring that overhead inline with every authenticated request.

As I mentioned, I don't have a use case for it at the moment. I just wanted to get a consistent behavior. When using DI on methods, one gets a new value on every invocation. But actually it shouldn't be necessary on classes. Reducing runtime overhead is a good point.

I was just curious about the case mentioned in your [second link](https://psamsotha.github.io/jersey/2015/12/16/request-scope-into-singleton-scope.html). As the last section describes, there seems to be a bug with the scopes, but that should be good for us.

**Pull request merged**
