### PR TITLE
Adding a sample Integrationtest using junit5 to reproduce issue #2274

### PR DESCRIPTION
**Pull request by edovale**
###### Problem:
Explained in issue #2274
###### Solution:
No Solution.
###### Result:
I put my junit5 integration test but for some reason I can't get maven to pick up any tests.

### CODE REVIEW

**Comment by edovale** [comment]
For some reason the tests in the example application are not getting picked up by surefire.

**Comment by arteam** [comment]
It looks like the tests pass with Maven... Could be this some issue with the JUnit5 intergration of your IDE?

**Comment by edovale** [comment]
@arteam Are you sure the test is running? I was able to replicate the behaviour running straight form maven.

**Comment by arteam** [comment]
For some reason Maven skips the all tests for `dropwizard-example`, that's why the tests are green. Maybe it some bug in the surefire plugin, when you mix JUnit4 and 5 tests.  But, I can run the JUnit5 test from the IDE (Intellij) with one change: You don't need to invoke `ResourceHelpers.resourceFilePath` twice to calculate a path to the config file.

**Comment by edovale** [comment]
That is a good catch @arteam but I fail to see how that could prevent a command from running. Can you explain this?

**Comment by arteam** [comment]
Yes, that's typo doesn't seem relevant to me, too. Can you try to isolate the issue by removing the all JUnit4 tests, so the surefire plugin picks up only the Junit5 test?

**Comment by isaki-x** [comment]
Rename the file to something *Test.java. By default, Maven only runs test that have classes that follow this naming convention.

**Comment by edovale** [comment]
I have renamed the Test and still maven is not picking it up.
I have also updated the junit5 deps to the latest.

**Comment by nickbabcock** [comment]
Adapting this PR to use `junit-jupiter-engine:5.2.0` and `junit-platform-surefire-provider:1.2.0` I see 

> [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.114 s - in com.example.helloworld.JUnit5IntegrationTest

So it looks like the tests have been picked up. Maybe I'm missing something.

**Comment by joschi** [comment]
@edovale The tests are being picked up (as @nickbabcock already mentioned) and are running successfully.

Build output from https://api.travis-ci.org/v3/job/399178141/log.txt:
```text
[INFO] --- maven-surefire-plugin:2.22.0:test (default-test) @ dropwizard-example ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.example.helloworld.JUnit5IntegrationTest
INFO  [2018-07-02 15:48:56,351] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2018-07-02 15:48:56,365] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2018-07-02 15:48:56,369] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: assets for path /assets/*
INFO  [2018-07-02 15:48:56,763] org.hibernate.Version: HHH000412: Hibernate Core {5.2.15.Final}
INFO  [2018-07-02 15:48:56,765] org.hibernate.cfg.Environment: HHH000206: hibernate.properties not found
INFO  [2018-07-02 15:48:56,793] io.dropwizard.hibernate.SessionFactoryFactory: Entity classes: [com.example.helloworld.core.Person]
INFO  [2018-07-02 15:48:56,887] org.hibernate.annotations.common.Version: HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
INFO  [2018-07-02 15:48:57,797] org.hibernate.dialect.Dialect: HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
INFO  [2018-07-02 15:48:58,407] org.hibernate.type.BasicTypeRegistry: HHH000270: Type registration [java.util.Currency] overrides previous : org.hibernate.type.CurrencyType@166e516
INFO  [2018-07-02 15:48:58,409] org.hibernate.type.BasicTypeRegistry: HHH000270: Type registration [java.time.Duration] overrides previous : org.hibernate.type.DurationType@570ae820
INFO  [2018-07-02 15:48:58,410] org.hibernate.type.BasicTypeRegistry: HHH000270: Type registration [java.time.Instant] overrides previous : org.hibernate.type.InstantType@2417a963
INFO  [2018-07-02 15:48:58,411] org.hibernate.type.BasicTypeRegistry: HHH000270: Type registration [java.time.LocalDate] overrides previous : org.hibernate.type.LocalDateType@285446f0
INFO  [2018-07-02 15:48:58,412] org.hibernate.type.BasicTypeRegistry: HHH000270: Type registration [java.time.LocalDateTime] overrides previous : org.hibernate.type.LocalDateTimeType@1eac48b9
INFO  [2018-07-02 15:48:58,413] org.hibernate.type.BasicTypeRegistry: HHH000270: Type registration [java.time.LocalTime] overrides previous : org.hibernate.type.LocalTimeType@1ee7e8a4
INFO  [2018-07-02 15:48:58,415] org.hibernate.type.BasicTypeRegistry: HHH000270: Type registration [java.time.OffsetDateTime] overrides previous : org.hibernate.type.OffsetDateTimeType@7a206aa
INFO  [2018-07-02 15:48:58,416] org.hibernate.type.BasicTypeRegistry: HHH000270: Type registration [java.time.OffsetTime] overrides previous : org.hibernate.type.OffsetTimeType@dcba368
INFO  [2018-07-02 15:48:58,417] org.hibernate.type.BasicTypeRegistry: HHH000270: Type registration [java.time.ZonedDateTime] overrides previous : org.hibernate.type.ZonedDateTimeType@715ecbe8
INFO  [2018-07-02 15:48:58,797] org.hibernate.hql.internal.QueryTranslatorFactoryInitiator: HHH000397: Using ASTQueryTranslatorFactory
INFO  [2018-07-02 15:48:59,032] io.dropwizard.server.ServerFactory: Starting hello-world
                           web-scale hello world dP for the web
                                                 88
  .d8888b. dP.  .dP .d8888b. 88d8b.d8b. 88d888b. 88 .d8888b.
  88ooood8  `8bd8'  88'  `88 88'`88'`88 88'  `88 88 88ooood8
  88.  ...  .d88b.  88.  .88 88  88  88 88.  .88 88 88.  ...
  `88888P' dP'  `dP `88888P8 dP  dP  dP 88Y888P' dP `88888P'
                                        88
                                        dP
INFO  [2018-07-02 15:48:59,224] org.eclipse.jetty.setuid.SetUIDListener: Opened application@160e2e68{HTTP/1.1,[http/1.1]}{0.0.0.0:45447}
INFO  [2018-07-02 15:48:59,225] org.eclipse.jetty.setuid.SetUIDListener: Opened admin@2815292a{HTTP/1.1,[http/1.1]}{0.0.0.0:35193}
INFO  [2018-07-02 15:48:59,230] org.eclipse.jetty.server.Server: jetty-9.4.11.v20180605; built: 2018-06-05T18:24:03.829Z; git: d5fc0523cfa96bfebfbda19606cad384d772f04c; jvm 1.8.0_141-8u141-b15-3~14.04-b15
WARN  [2018-07-02 15:49:00,154] org.glassfish.jersey.internal.inject.Providers: A provider com.example.helloworld.resources.PeopleResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider com.example.helloworld.resources.PeopleResource will be ignored. 
WARN  [2018-07-02 15:49:00,155] org.glassfish.jersey.internal.inject.Providers: A provider com.example.helloworld.resources.HelloWorldResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider com.example.helloworld.resources.HelloWorldResource will be ignored. 
WARN  [2018-07-02 15:49:00,155] org.glassfish.jersey.internal.inject.Providers: A provider com.example.helloworld.resources.ViewResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider com.example.helloworld.resources.ViewResource will be ignored. 
WARN  [2018-07-02 15:49:00,155] org.glassfish.jersey.internal.inject.Providers: A provider com.example.helloworld.resources.ProtectedResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider com.example.helloworld.resources.ProtectedResource will be ignored. 
WARN  [2018-07-02 15:49:00,156] org.glassfish.jersey.internal.inject.Providers: A provider com.example.helloworld.resources.FilteredResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider com.example.helloworld.resources.FilteredResource will be ignored. 
WARN  [2018-07-02 15:49:00,157] org.glassfish.jersey.internal.inject.Providers: A provider com.example.helloworld.resources.PersonResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider com.example.helloworld.resources.PersonResource will be ignored. 
INFO  [2018-07-02 15:49:00,559] io.dropwizard.jersey.DropwizardResourceConfig: The following paths were found for the configured resources:

    GET     /filteredhello (com.example.helloworld.resources.FilteredResource)
    GET     /hello-world (com.example.helloworld.resources.HelloWorldResource)
    POST    /hello-world (com.example.helloworld.resources.HelloWorldResource)
    GET     /hello-world/date (com.example.helloworld.resources.HelloWorldResource)
    GET     /people (com.example.helloworld.resources.PeopleResource)
    POST    /people (com.example.helloworld.resources.PeopleResource)
    GET     /people/{personId} (com.example.helloworld.resources.PersonResource)
    GET     /people/{personId}/view_freemarker (com.example.helloworld.resources.PersonResource)
    GET     /people/{personId}/view_mustache (com.example.helloworld.resources.PersonResource)
    GET     /protected (com.example.helloworld.resources.ProtectedResource)
    GET     /protectedadmin (com.example.helloworld.resources.ProtectedResource)
    GET     /views/iso88591.ftl (com.example.helloworld.resources.ViewResource)
    GET     /views/iso88591.mustache (com.example.helloworld.resources.ViewResource)
    GET     /views/utf8.ftl (com.example.helloworld.resources.ViewResource)
    GET     /views/utf8.mustache (com.example.helloworld.resources.ViewResource)

INFO  [2018-07-02 15:49:00,571] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@4b4898c8{/,null,AVAILABLE}
INFO  [2018-07-02 15:49:00,580] io.dropwizard.setup.AdminEnvironment: tasks = 

    POST    /tasks/echo (com.example.helloworld.tasks.EchoTask)
    POST    /tasks/log-level (io.dropwizard.servlets.tasks.LogConfigurationTask)
    POST    /tasks/gc (io.dropwizard.servlets.tasks.GarbageCollectionTask)

INFO  [2018-07-02 15:49:00,595] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@75c5c547{/,null,AVAILABLE}
INFO  [2018-07-02 15:49:00,615] org.eclipse.jetty.server.AbstractConnector: Started application@160e2e68{HTTP/1.1,[http/1.1]}{0.0.0.0:45447}
INFO  [2018-07-02 15:49:00,617] org.eclipse.jetty.server.AbstractConnector: Started admin@2815292a{HTTP/1.1,[http/1.1]}{0.0.0.0:35193}
INFO  [2018-07-02 15:49:00,618] org.eclipse.jetty.server.Server: Started @10413ms
INFO  [2018-07-02 15:49:01,859] liquibase.executor.jvm.JdbcExecutor: SELECT COUNT(*) FROM PUBLIC.DATABASECHANGELOGLOCK
INFO  [2018-07-02 15:49:01,886] liquibase.executor.jvm.JdbcExecutor: CREATE TABLE PUBLIC.DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID))
INFO  [2018-07-02 15:49:01,912] liquibase.executor.jvm.JdbcExecutor: SELECT COUNT(*) FROM PUBLIC.DATABASECHANGELOGLOCK
INFO  [2018-07-02 15:49:01,921] liquibase.executor.jvm.JdbcExecutor: DELETE FROM PUBLIC.DATABASECHANGELOGLOCK
INFO  [2018-07-02 15:49:01,925] liquibase.executor.jvm.JdbcExecutor: INSERT INTO PUBLIC.DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, FALSE)
INFO  [2018-07-02 15:49:01,932] liquibase.executor.jvm.JdbcExecutor: SELECT LOCKED FROM PUBLIC.DATABASECHANGELOGLOCK WHERE ID=1
INFO  [2018-07-02 15:49:01,951] liquibase.lockservice.StandardLockService: Successfully acquired change log lock
INFO  [2018-07-02 15:49:03,373] liquibase.changelog.StandardChangeLogHistoryService: Creating database history table with name: PUBLIC.DATABASECHANGELOG
INFO  [2018-07-02 15:49:03,377] liquibase.executor.jvm.JdbcExecutor: CREATE TABLE PUBLIC.DATABASECHANGELOG (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED TIMESTAMP NOT NULL, ORDEREXECUTED INT NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION VARCHAR(255), COMMENTS VARCHAR(255), TAG VARCHAR(255), LIQUIBASE VARCHAR(20), CONTEXTS VARCHAR(255), LABELS VARCHAR(255), DEPLOYMENT_ID VARCHAR(10))
INFO  [2018-07-02 15:49:03,395] liquibase.executor.jvm.JdbcExecutor: SELECT COUNT(*) FROM PUBLIC.DATABASECHANGELOG
INFO  [2018-07-02 15:49:03,396] liquibase.changelog.StandardChangeLogHistoryService: Reading from PUBLIC.DATABASECHANGELOG
INFO  [2018-07-02 15:49:03,398] liquibase.executor.jvm.JdbcExecutor: SELECT * FROM PUBLIC.DATABASECHANGELOG ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
INFO  [2018-07-02 15:49:03,400] liquibase.executor.jvm.JdbcExecutor: SELECT COUNT(*) FROM PUBLIC.DATABASECHANGELOGLOCK
INFO  [2018-07-02 15:49:03,415] liquibase.executor.jvm.JdbcExecutor: CREATE TABLE PUBLIC.people (id BIGINT AUTO_INCREMENT NOT NULL, fullName VARCHAR(255) NOT NULL, jobTitle VARCHAR(255), CONSTRAINT PK_PEOPLE PRIMARY KEY (id))
INFO  [2018-07-02 15:49:03,440] liquibase.changelog.ChangeSet: Table people created
INFO  [2018-07-02 15:49:03,442] liquibase.changelog.ChangeSet: ChangeSet migrations.xml::1::codahale ran successfully in 28ms
INFO  [2018-07-02 15:49:03,445] liquibase.executor.jvm.JdbcExecutor: SELECT MAX(ORDEREXECUTED) FROM PUBLIC.DATABASECHANGELOG
INFO  [2018-07-02 15:49:03,458] liquibase.executor.jvm.JdbcExecutor: INSERT INTO PUBLIC.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1', 'codahale', 'migrations.xml', NOW(), 1, '8:a466b7f04155c06f80453d6d5a36b55c', 'createTable tableName=people', '', 'EXECUTED', NULL, NULL, '3.6.1', '0546543401')
INFO  [2018-07-02 15:49:03,465] liquibase.lockservice.StandardLockService: Successfully released change log lock
INFO  [2018-07-02 15:49:04,294] org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: Session Metrics {
    122910 nanoseconds spent acquiring 2 JDBC connections;
    73096 nanoseconds spent releasing 2 JDBC connections;
    21766662 nanoseconds spent preparing 1 JDBC statements;
    3440121 nanoseconds spent executing 1 JDBC statements;
    0 nanoseconds spent executing 0 JDBC batches;
    0 nanoseconds spent performing 0 L2C puts;
    0 nanoseconds spent performing 0 L2C hits;
    0 nanoseconds spent performing 0 L2C misses;
    5172760 nanoseconds spent executing 1 flushes (flushing a total of 1 entities and 0 collections);
    0 nanoseconds spent executing 0 partial-flushes (flushing a total of 0 entities and 0 collections)
}
127.0.0.1 - - [02/Jul/2018:15:49:04 +0000] "POST /people HTTP/1.1" 200 67 "-" "Jersey/2.27 (HttpUrlConnection 1.8.0_141)" 359
INFO  [2018-07-02 15:49:04,387] org.eclipse.jetty.server.AbstractConnector: Stopped application@160e2e68{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
INFO  [2018-07-02 15:49:04,388] org.eclipse.jetty.server.AbstractConnector: Stopped admin@2815292a{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
INFO  [2018-07-02 15:49:04,391] org.eclipse.jetty.server.handler.ContextHandler: Stopped i.d.j.MutableServletContextHandler@75c5c547{/,null,UNAVAILABLE}
127.0.0.1 - - [02/Jul/2018:15:49:04 +0000] "GET /hello-world?name=Dr.+IntegrationTest HTTP/1.1" 200 48 "-" "Jersey/2.27 (HttpUrlConnection 1.8.0_141)" 36
INFO  [2018-07-02 15:49:04,409] org.eclipse.jetty.server.handler.ContextHandler: Stopped i.d.j.MutableServletContextHandler@4b4898c8{/,null,UNAVAILABLE}
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.282 s - in com.example.helloworld.JUnit5IntegrationTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by joschi** [comment]
I'm closing this PR because everything seems to be working.

**Pull request closed without merging**
