### PR TITLE
Update Jetty to 9.3.11.v20160721

### PR DESCRIPTION
**Pull request by nickbabcock**
This PR supersedes #1608:

- By updating to a newer version of Jetty
- Fixing test case on windows due to window paths
- Fixing test failure found in #1608 with new exception comparison. Admittedly, it seems like a worse exception message to test against (`SSLException` vs `SSLHandshakeException`)

### CODE REVIEW

**Comment by joschi** [comment]
LGTM. 👍 

Could you please add this to the release notes, too?

**Comment by nickbabcock** [comment]
Just pushed a commit to this PR that starts the 1.1.0 release notes.

**Comment by jplock** [comment]
Once the release notes are in, I can go back and update it for the PR's I merged earlier.

**Comment by joschi** [comment]
Thanks!

**Pull request merged**
