### PR TITLE
Fix DefaultLoggingFactoryTest on Windows

### PR DESCRIPTION
**Pull request by nickbabcock**
Also it is unnecessary to delete the log files after the test is done
because the log files are zeroed out when the test runs.

### CODE REVIEW

**Comment by arteam** [comment]
It's a bummer, that we can't run the build on Windows in Travis CI. The amount of Windows test fixes is a clear sign, that there are plenty of developers on this OS, who hack on Dropwizard.

**Comment by joschi** [comment]
> Also it is unnecessary to delete the log files after the test is done because the log files are zeroed out when the test runs.

I don't agree. If the log files aren't removed after the test run, we don't know if they were created in the following test runs or if there was an error – unless we clean the complete working directory (e. g. by running `mvn clean`).

**Comment by arteam** [comment]
I don't like the proposed solution, because it writes log files to the current directory with source code.

It would be better if we created a temporary file by `File.createTempFile` and passed its path to the configuration factory by a system property. The problem is that `dw.loggers.com.example.newApp.appenders.currentLogFilename` will not work, because the parser
will treat _com_, _example_, and _newApp_ as keys, but not as a whole property. And I don't know how to escape dots.

**Comment by arteam** [comment]
As a sidenote, in future we should probably retrofit the parser to support escaping with something like this: `dw.loggers.com{dot}example{dot}newApp.appenders[0].currentLogFilename`

**Comment by nickbabcock** [comment]
I was following the example set in other tests in `FileAppenderFactoryTest`, which have the same behavior (writes log files to current directory and doesn't delete them afterwards). I can rework the tests to see if I can take advantage of `TemporaryFolder`

**Comment by nickbabcock** [comment]
The commit I just pushed fixes everything in `dropwizard-logging` that outputs logs to the current working directory. Now logs are stored in a cross platform temporary folder. It's not exactly the prettiest but leaves `logging_advanced.yml` in a sane state, so that it can be used as an example.

**Comment by arteam** [comment]
What do you think about using `StrSubstitutor`?
We could replace actual locations in the yml file by variables and then initialize them in runtime.
Something like this:
````yml
level: INFO
loggers:
  "com.example.app": INFO
  "com.example.newApp":
    level: DEBUG
    appenders:
      - type: file
        currentLogFilename: ${new_app_log}
        archivedLogFilenamePattern: ${new_app_archive_log}
        logFormat: "%-5level %logger: %msg%n"
        archivedFileCount: 5
  "com.example.legacyApp":
    level: DEBUG
appenders:
  - type: console
  - type: file
    currentLogFilename: ${default_log}
    archivedLogFilenamePattern: ${default_archive_log}
    logFormat: "%-5level %logger: %msg%n"
    archivedFileCount: 5
````
```java
final File newAppLog = folder.newFile("example-new-app.log");
final File defaultLog = folder.newFile("example.log");
final StrSubstitutor substitutor = new StrSubstitutor(ImmutableMap.of(
        "new_app_log", newAppLog.getAbsolutePath(),
        "new_app_archive_log", "/tmp/example-new-app-%d.log.gz",
        "default_log", defaultLog.getAbsolutePath(),
        "default_archive_log", "/tmp/example-%d.log.gz"
));

final String filePath = new File(Resources.getResource("yaml/logging_advanced.yml")
.toURI()).getAbsolutePath();
config = factory.build(new SubstitutingSourceProvider(
new FileConfigurationSourceProvider(), substitutor), filePath);
```

**Comment by nickbabcock** [comment]
Confirmed.  That is prettier code. I shortened it to use 2 substituted variables instead of 4.

**Comment by arteam** [comment]
Great. This looks a lot better now.

**Pull request merged**
