### PR TITLE
Add SPI for RequestLogFactory

### PR DESCRIPTION
**Pull request by mwhipple**
Allows for overriding of `RequestLog` implementation such as to allow use of logback-access

### CODE REVIEW

**Comment by arteam** [comment]
Thanks! Applied to master in 05d3fcd with some enhancements.

**Comment by mattnelson** [comment]
@mwhipple Do you have an implementation using these changes for logback-access? I am also looking for this feature and would like to avoid reimplementing.

**Comment by mwhipple** [comment]
@mattnelson I should be able to get something together that I can post for you in some form if not as a directly usable artifact tomorrow. The working implementation with logback-access that I have doesn't use this change and instead extends the top level configuration object (the ugliness of which inspired the PR)

**Comment by mwhipple** [comment]
I'd left out extending `Discoverable` so the logback access module won't be as convenient to use pending https://github.com/dropwizard/dropwizard/pull/1412, but it should be able to be handled with an explicit registration of a Jackson module in the consuming service. I extracted most of the implementation and I'll publish the present state in the morning (should work but could stand cleanup) and work on info about the Jackson module when time allows.

**Comment by mwhipple** [comment]
@mattnelson https://github.com/mwhipple/dropwizard-logback-access - still awaiting enough time to be in a presentable state and published but at least enough to start with.

**Pull request closed without merging**
