### PR TITLE
Remove public modifiers from tests

### PR DESCRIPTION
**Pull request by rhowe**
JUnit 5 no longer requires this.

Generated via:

    sed -i '/@\(Test\|BeforeEach\|AfterEach\)/{n;s/public void/void/}' \
        $(git grep -lF '@Test' */src/test/)

Sadly, Jersey's `JerseyTest` base class declares its `BeforeEach`/`AfterEach` methods public so we have to follow suit there.

### CODE REVIEW

**Comment by rhowe** [comment]
Looks like `JdbiHealthCheckTest#testNoTimeoutReturnsHealthy` might be a bit flaky?

**Review by jan-molak — APPROVED** [review]
This is a good suggestion, JUnit 5 test methods don't need to be public ([source](https://junit.org/junit5/docs/current/user-guide/#writing-tests-classes-and-methods))

**Review by jplock — APPROVED** [review]

**Comment by rhowe** [comment]
Just checked sonar and I think this has reduced the "code smell" count in Sonar from just over 2,000 to just under 1,000 :+1:

**Comment by rhowe** [comment]
Then again, seems I was a bit too keen: https://github.com/dropwizard/dropwizard/pull/3727

**Pull request merged**
