### PR TITLE
Revert "Update dependency jakarta.ws.rs:jakarta.ws.rs-api to v3.1.0 (release/4.0.x)"

### PR DESCRIPTION
**Pull request by joschi**
Reverts dropwizard/dropwizard#5230

### CODE REVIEW

**Comment by joschi** [comment]
Let's see how quickly the Jersey project will release a compatible version. 😅

**Comment by zUniQueX** [comment]
That one isn't that problematic IMO. Jersey 3.1.0 should be already released, we'll see when it's out.

**Comment by zUniQueX** [comment]
The [roadmap](https://github.com/eclipse-ee4j/jersey/wiki/Road-Map#planned) of the Jersey project states the release to be planned for may.

**Comment by zUniQueX** [comment]
The wiki has been updated and Jersey 3.1.0 is slated for september. If the release would be delivered this month, I think we can wait for it.

**Comment by zUniQueX** [comment]
Jersey 3.1.0 finally appeared in Maven central.

**Review by zUniQueX — APPROVED** [review]

**Pull request merged**
