### PR TITLE
Fix MetricFilter per #890; add support for regex-based filters per #884

### PR DESCRIPTION
**Pull request by eepstein**
Updated docs as well.
Unit test covers includesRegex but not excludesRegex (can add if required)

### CODE REVIEW

**Comment by arteam** [comment]
@eepstein Could you, please, update your PR according to the changes made in #884?
It's already merged to master.

**Comment by eepstein** [comment]
Yes, will do.

**Comment by eepstein** [comment]
Updated.

**Comment by arteam** [comment]
I've rebased the changes and merged them with small improvements.
Thanks, @eepstein, for your steady work on this!

**Pull request closed without merging**
