### PR TITLE
SelfValidation annotation as an alternative to ValidationMethod

### PR DESCRIPTION
**Pull request by manuel-hegner**
This pull request solves my feature request issue #2140 .
It adds the two Annoations @SelfValidation and @SelfValidating. An example of how to use it:
```java
@SelfValidating
public class Example {
    private int a = 3;
    private int b = 6;

    @SelfValidation
    public void validOnlyIfEven(ViolationCollector col) {
        if(a+b % 2 != 0)
            col.addViolation("a+b must be an even value. At the moment it is "+a+"+"+b+"="+(a+b));
    }
}
```

What do you think of it? If this solution is okay with you (especially the names of annotations) I would write a paragraph for the documentation.

### CODE REVIEW

**Comment by manuel-hegner** [comment]
Ich think performance should not be a problem with how the code turned out. Since I use code generation instead of reflection the runtime overhead should be only once per class. But it is never a bad idea to have a benchmark and I look into writing one.

**Comment by manuel-hegner** [comment]
Finally got around to writing a benchmark. As predicted the code generation overhead is negligible. @SelfValidating is still slower than ValidationMethod because Hibernate needs to reevaluate the given error string (templating engine) every time instead of only once per annotation, but it is still much faster than some other hibernate validation annotations.

Here the results:
```
SelfValidatingBenchmark.selfValidating    avgt    8  3243,249 ± 41,973  ns/op
SelfValidatingBenchmark.validationMethod  avgt    8   568,652 ± 10,330  ns/op
```

**Comment by nickbabcock** [comment]
It just occurred to me. Would you use a custom `ExceptionMapper<JerseyViolationException>` for your `@SelfValidation` example, due to the caching nature of the default exception mapper? (Don't change your PR, just curious, as this got me thinking)

**Comment by arteam** [comment]
Wow, that looks pretty great! @manuel-hegner Thanks for the contribution!

Very interesting to see how `@SelfValidation` performs in comparasion to `@ValidationMethod`. I think it maybe very useful for users who like put validation in domain objects and concerned about performance.

**Pull request merged**
