### PR TITLE
Flush loggers on cleanup, don't destroy (back-port for Dropwizard 1.1.0)

### PR DESCRIPTION
**Pull request by joschi**
(cherry picked from commit 6c76c27c0cf637073dc7a72ae63a97dc5ff9b78f)

Refs #1947

### CODE REVIEW

**Comment by nickbabcock** [comment]
I'm fine with having this in 1.1.0, but we'll need another RC (just it in case it wasn't planned) to ensure that this doesn't break an edge case 😄

**Comment by arteam** [comment]
I can cut a RC today.

**Comment by nickbabcock** [comment]
@arteam, not sure if this is normal, but it's been 6 hours since you tagged rc2 and and rc2 isn't out on maven central

**Comment by arteam** [comment]
My fault, I haven't promoted the release candidate, other things popped up during the day. Doing that right now.

**Comment by arteam** [comment]
Should be released now in the central repository, but it takes some time for a release to sync on all replicas.

**Pull request merged**
