### PR TITLE
Log sub resource locators correctly

### LINKED ISSUE #1222: NPE in DropwizardResourceConfig$EndpointLogger.populate
Using 0.9.0-rc3, I'm getting an NPE at startup. Here is the stack trace.

```
! java.lang.NullPointerException: null
! at io.dropwizard.jersey.DropwizardResourceConfig$EndpointLogger.populate(DropwizardResourceConfig.java:173) ~[dropwizard-jersey-0.9.0-rc3.jar:0.9.0-rc3]
! at io.dropwizard.jersey.DropwizardResourceConfig$EndpointLogger.populate(DropwizardResourceConfig.java:165) ~[dropwizard-jersey-0.9.0-rc3.jar:0.9.0-rc3]
! at io.dropwizard.jersey.DropwizardResourceConfig$EndpointLogger.populate(DropwizardResourceConfig.java:184) ~[dropwizard-jersey-0.9.0-rc3.jar:0.9.0-rc3]
! at io.dropwizard.jersey.DropwizardResourceConfig$EndpointLogger.populate(DropwizardResourceConfig.java:165) ~[dropwizard-jersey-0.9.0-rc3.jar:0.9.0-rc3]
! at io.dropwizard.jersey.DropwizardResourceConfig$EndpointLogger.populate(DropwizardResourceConfig.java:161) ~[dropwizard-jersey-0.9.0-rc3.jar:0.9.0-rc3]
! at io.dropwizard.jersey.DropwizardResourceConfig.getEndpointsInfo(DropwizardResourceConfig.java:130) ~[dropwizard-jersey-0.9.0-rc3.jar:0.9.0-rc3]
! at io.dropwizard.jersey.DropwizardResourceConfig.logComponents(DropwizardResourceConfig.java:80) ~[dropwizard-jersey-0.9.0-rc3.jar:0.9.0-rc3]
! at io.dropwizard.jersey.DropwizardResourceConfig$ComponentLoggingListener.onEvent(DropwizardResourceConfig.java:240) ~[dropwizard-jersey-0.9.0-rc3.jar:0.9.0-rc3]
! at org.glassfish.jersey.server.internal.monitoring.CompositeApplicationEventListener.onEvent(CompositeApplicationEventListener.java:74) ~[jersey-server-2.19.jar:na]
! at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:615) ~[jersey-server-2.19.jar:na]
! at org.glassfish.jersey.server.ApplicationHandler.access$500(ApplicationHandler.java:183) ~[jersey-server-2.19.jar:na]
! at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:349) ~[jersey-server-2.19.jar:na]
! at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:346) ~[jersey-server-2.19.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.19.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.19.jar:na]
! at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:255) ~[jersey-common-2.19.jar:na]
! at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:346) ~[jersey-server-2.19.jar:na]
! at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:339) ~[jersey-container-servlet-core-2.19.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:170) ~[jersey-container-servlet-core-2.19.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:362) ~[jersey-container-servlet-core-2.19.jar:na]
! at javax.servlet.GenericServlet.init(GenericServlet.java:244) ~[javax.servlet-api-3.1.0.jar:3.1.0]
! at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:612) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:395) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
! at com.codahale.metrics.jetty9.InstrumentedHandler.doStart(InstrumentedHandler.java:103) [metrics-jetty9-3.1.2.jar:3.1.2]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.server.handler.RequestLogHandler.doStart(RequestLogHandler.java:140) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:232) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.server.Server.start(Server.java:387) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.server.Server.doStart(Server.java:354) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43) [dropwizard-core-0.9.0-rc3.jar:0.9.0-rc3]
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:41) [dropwizard-core-0.9.0-rc3.jar:0.9.0-rc3]
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77) [dropwizard-core-0.9.0-rc3.jar:0.9.0-rc3]
! at io.dropwizard.cli.Cli.run(Cli.java:70) [dropwizard-core-0.9.0-rc3.jar:0.9.0-rc3]
! at io.dropwizard.Application.run(Application.java:80) [dropwizard-core-0.9.0-rc3.jar:0.9.0-rc3]
! at edu.wvu.stat.rc2.Rc2Application.main(Rc2Application.java:31) [classes/:na]
```

I'm trying to use a sub-resource locator. Looking in the eclipse debugger in the third frame of populate (line 184), path is `/workspaces/{id}/files`, klass is `class edu.wvu.stat.rc2.resources.WorkspaceResource`, and method is

```
ResourceMethod{httpMethod=null, consumedTypes=[], producedTypes=[],
suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS,
invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class
edu.wvu.stat.rc2.resources.WorkspaceResource,
handlerConstructors=[org.glassfish.jersey.server.model.
HandlerConstructor@2e32fc22,
org.glassfish.jersey.server.model.HandlerConstructor@3f5156a6]},
definitionMethod=public java.lang.Class
edu.wvu.stat.rc2.resources.WorkspaceResource.fileResource(int),
parameters=[Parameter [type=int, source=id, defaultValue=null]],
responseType=java.lang.Class<edu.wvu.stat.rc2.resources.FileResource>},
nameBindings=[]}
```

In the next frame up, klass is `java.lang.Class` as a result of `method.getInvocable().getRawResponseType()` in the previous frame. This line calls line 165
which calls `Resource.from(java.lang.Class)`, which then triggers the NPE in the next frame on line 173.  
FileResource.java is 

```java
@Produces(MediaType.APPLICATION_JSON)
public class FileResource extends BaseResource {
	final static Logger log= LoggerFactory.getLogger(FileResource.class);
	
	private int _wspaceId;
	
	@Context UriInfo _uriInfo;
	
	public FileResource() {}
	
	public FileResource(int wspaceId) {
		_wspaceId = wspaceId;
	}
	
	@GET
	public String getFileList() {
		log.info("wspace");;
		return "{\"wspaceId\":" + _uriInfo.getPathParameters().get("wspaceId") + "}";
	}
}
```

and the relevant part of WorkspaceResource is

```java
@Path("/workspaces")
@Produces(MediaType.APPLICATION_JSON)
public class WorkspaceResource extends BaseResource {
	final static Logger log= LoggerFactory.getLogger(WorkspaceResource.class);
	
	public WorkspaceResource() {
		super();
		
	}

	public WorkspaceResource(DBI dbi, RCUser user) {
		super(dbi, user);
		
	}

	@Path("{id}/files")
	public Class<FileResource> fileResource(@PathParam("id") int wspaceId) {
		log.info(String.format("request for wspace files %d", wspaceId));
		return FileResource.class;
	}
```

Regardless of any errors I've made, dropwizard really should catch this kind of error and at least report a failure (especially since this is appears to just be logging code). Without the debugger breaking on the first throw, the stack trace has something like 5 nested exceptions that provide no useful information about what went wrong.

It would be really helpful if when releases are pushed the source and javadoc artifacts were pushed, too. That way eclipse could show help when working with dropwizard.

### LINKED ISSUE #1257: Child resource injection not working
Following the jersey documentation this is supposed to work and it has worked before but not with 0.9.0-rc5:
```
@Path("logg_ut")
public Class<LoggUtResource> loggUtResource(){
	return LoggUtResource.class;
}
```

However this works:
```
@Path("logg_ut")
public LoggUtResource loggUtResource(){
	return new LoggUtResource(null, null, null);
}
```

Debugging I found this in DropwizardResourceConfig.java:168
```
for (ResourceMethod method : resource.getResourceMethods()) {
     endpointLogLines.add(new EndpointLogLine(method.getHttpMethod(), basePath, klass));
}
```
The resource contains  0 resouce methods but one and causes a null pointer exception :
_Resource{"/lobby/", 1 child resources, 0 resource methods, 0 sub-resource locator, 1 method handler classes, 0 method handler instances}_

And then:
_resource: null_ for the sub resource

EDIT:
I found this in line 179:
```populate(path, method.getInvocable().getRawResponseType(), true, endpointLogLines);```
rawresponsetype: class java.lang.Class
responsetype: java.lang.Class<com.holtebu.bosetterne.service.resources.lobby.LoggUtResource>

I hope I did'nt miss anything and perhaps Dropwizard isn't supposed to support this feature?

### PR DESCRIPTION
**Pull request by nickbabcock**
This should close #1257.

@espenhoh let me know if I missed anything.

EDIT: Closes #1222 too

### CODE REVIEW

**Comment by arteam** [comment]
Conceptually this looks good to me. 

I have one only proposal: what do you think about using [java-classmate](https://github.com/FasterXML/java-classmate) for type resolving? It provides a nice API for working with `java.lang.reflect.Type` stuff, which is more readable than pure reflection. I think, we could strip the fix down to something like that:

```java
final ResolvedType responseType = TYPE_RESOLVER
                                 .resolve(method.getInvocable().getResponseType());
final Class<?> erasedType = !responseType.getTypeBindings().isEmpty() ?
        responseType.getTypeBindings().getBoundType(0).getErasedType() :
        responseType.getErasedType();
populate(path, erasedType, true, endpointLogLines);
```

**Comment by nickbabcock** [comment]
Done. I'm all for ways to make code simpler!

**Comment by arteam** [comment]
Thanks!

**Comment by espenhoh** [comment]
Yes works :). Thanks a lot! There are a lot of tests breaking, is it normal?

**Comment by nickbabcock** [comment]
What do you mean tests are failing? The continuous integration tool dropwizard uses (Travis CI), occasionally breaks, so tests failing on Travis is normally not a big deal. If you have found additional issues with dropwizard, feel free to report them.

**Comment by espenhoh** [comment]
I am not familiar with Travis CI or continuos integration, is it something I should look into?
But then I guess it's under control and I will build dropwizard without tests :)

**Comment by nickbabcock** [comment]
Oh, I see, your local build is failing. Your local build shouldn't be failing (though even I get the occasional socket read time out or address already in use)

**Pull request merged**
