### PR TITLE
3311 replace jsr305 annotations with spotbugs-annotations

### PR DESCRIPTION
**Pull request by olegzzz**
###### Problem:
Solution to issue https://github.com/dropwizard/dropwizard/issues/3311

###### Solution:
Replace classes from jsr305 with classes from spotbugs-annotations.

###### Result:
Note that jsr305 dependency is still present at compile time through some 3rd party dependencies. When removed completely, there are warnings like this (although tests pass)
```
[WARNING] unknown enum constant When.UNKNOWN
```
most likely caused by Mockito use of `javax.annotation.meta.When`

### CODE REVIEW

**Comment by joschi** [comment]
@olegzzz Thanks for your contribution!

Is there any particular advantage in using `spotbugs-annotations` over `jsr305`?

**Comment by olegzzz** [comment]
Wasn't the ask was to replace jsr305 annotations with spotbugs annotations?

**Comment by joschi** [comment]
@olegzzz Yes, but do you see any advantage in using one artifact over the other?

**Comment by brentryan** [comment]
The main advantage is to move onto something that is still supported. It appears that jsr305 has gone dormant and everything is moving away from its use: guava, micronaut are just a few...

**Comment by joschi** [comment]
> The main advantage is to move onto something that is still supported.

These are marker annotations, nothing which contains actual logic and it seems that currently more projects (static code analyzers) support the JSR 305 variants of these annotations than the SpotBugs ones.

> It appears that jsr305 has gone dormant and everything is moving away from its use: guava, micronaut are just a few...

At least Guava is only planning to do so but hasn't done so yet: https://github.com/google/guava/issues/2960

As for the choice of replacement, why SpotBugs and not for example [`org.jetbrains:annotations`](https://github.com/JetBrains/java-annotations)?

**Comment by brentryan** [comment]
Here's the example from micronaut PR https://github.com/micronaut-projects/micronaut-core/issues/1633

**Comment by joschi** [comment]
@dropwizard/committers Any opinion on this?
Should we target the change for Dropwizard 2.1.x?

**Comment by jplock** [comment]
I've been struggling with this one myself.  Even though the jsr305 annotations aren't "maintained", they are well supported and not likely to need changing.  I'd probably leave them using `javax.annotation` for now.

**Comment by olegzzz** [comment]
Closing this as not required.

**Pull request closed without merging**
