### PR TITLE
Remove Joda Time support

### PR DESCRIPTION
**Pull request by rhowe**
Remove the following classes from io.dropwizard.jersey.params:

- DateTimeParam
- DurationParam
- InstantParam
- LocalDateParam

These were deprecated and slated for removal in 3.0.0

Also, remove Joda Time from `dropwizard-jdbi3`, `dropwizard-jersey` and `dropwizard-hibernate`, removing it from Dropwizard altogether in favour of JSR310's `java.time.*` classes.

### CODE REVIEW

**Comment by rhowe** [comment]
Jackson.java still includes Jackson's `JodaModule`. Should this also go, along with the `jackson-datatype-joda` dependency?

**Comment by jplock** [comment]
@rhowe i would think so

**Comment by rhowe** [comment]
If you merge `release/2.1.x` into `release/3.0.x` then I can rebase the dropwizard-hibernate change out of this PR.

Do we need any docs for people migrating from Joda Time?

**Comment by joschi** [comment]
> If you merge `release/2.1.x` into `release/3.0.x` then I can rebase the dropwizard-hibernate change out of this PR.

I've merged `release/2.1.x` into `release/3.0.x`.

**Review by joschi — APPROVED** [review]

**Pull request merged**
