### PR TITLE
Add JerseyClientConfiguration option for disabling chunked encoding.

### LINKED ISSUE #403: JerseyHttpClient always uses chunked encoding for sending data, annoying lighttpd
If you use Dropwizard's JerseyHttpClient to POST data somewhere, it will always use chunked encoding which annoys simpler webservers like lighttpd massively:

```
POST / HTTP/1.1
Content-Type: application/json
Accept-Encoding: gzip
Transfer-Encoding: chunked
Host: 127.0.0.1:8000
Connection: Keep-Alive

2
{}
0

HTTP/1.1 411 Length Required
Content-Type: text/html
Content-Length: 357
Connection: close
Date: Thu, 03 Oct 2013 08:37:56 GMT
Server: lighttpd/1.4.28

[…]
```

This shouldn't really happen because Jersey's [ApacheHttpClient4Handler](https://java.net/projects/jersey/sources/svn/content/tags/jersey-1.17.1/jersey/contribs/jersey-apache-client4/src/main/java/com/sun/jersey/client/apache4/ApacheHttpClient4Handler.java?rev=5854) does use a `BufferedHttpEntity` unless requested otherwise (line 271ff).

Below you can find a simplish test case (I think the `Managed` stuff isn't really necessary, I just wanted to be sure everything is in a good state before I send my request). It won't happen in my naive JerseyClient implementation (switch the comments in `main`) and also won't happen with a `HttpClient` (switch the comments in `run`) unless you use a streaming `HttpEntity` and forget to wrap it in a `BufferedHttpEntity`.

Because it doesn't happen in `runNaiveJerseyClient` I think Dropwizard registers some magic which makes the Jersey client unhappy/forget to apply its `BufferedHttpEntity`. My guess is the gzip filter which is registered (at least I'm stepping through it with the debugger) even if I set `setGzipEnabledForRequests` to false. But I might be wrong.

```
public class TestService extends Service<Configuration> {
    private final static String URL = "http://127.0.0.1:8000/";

    public static void main(String[] args) throws Exception {
        TestService s = new TestService();
        s.run(args);
        //s.runNaiveJerseyClient();
    }

    public void initialize(Bootstrap<Configuration> bootstrap) {}

    public void run(Configuration config, Environment env) throws Exception {
        runJerseyClient(config, env);
        //runHttpClient(config, env);
        env.addResource(new Root());
    }
    private void runJerseyClient(Configuration config, Environment env) throws Exception  {
        final JerseyClientConfiguration clientConfig = new JerseyClientConfiguration();
        clientConfig.setGzipEnabledForRequests(false);
        final Client client = new JerseyClientBuilder()
            .using(clientConfig)
            .using(env)
            .withProperty(ClientConfig.PROPERTY_CHUNKED_ENCODING_SIZE, null)
            .build();
        client.addFilter(new LoggingFilter());
        env.manage(new Managed() {
            public void start() throws Exception {
                WebResource.Builder builder = client.resource(URL)
                        .type("application/json")
                        .entity(new HashMap<String, Object>());
                builder.post();
            }
            public void stop() throws Exception {}
        });
    }
    private void runNaiveJerseyClient() {
        Client client = Client.create();
        client.setChunkedEncodingSize(null);
        client.addFilter(new LoggingFilter());
        WebResource.Builder builder = client.resource(URL)
                .type("application/json")
                .entity(new HashMap<String, Object>());
        builder.post();
    }
    private void runHttpClient(Configuration config, Environment env) throws Exception {
        final HttpClientConfiguration clientConfig = new HttpClientConfiguration();
        final HttpClient client = new HttpClientBuilder()
            .using(clientConfig)
            .build();
        //final HttpEntity entity = new StringEntity("{}");
        final HttpEntity entity = new BufferedHttpEntity(new EntityTemplate(new ContentProducer() {
            public void writeTo(OutputStream out) throws IOException {
                out.write(new byte[]{'{', '}'});
            }
        }));
        env.manage(new Managed() {
            public void start() throws Exception {
                HttpPost post = new HttpPost(URL);
                post.setHeader("Content-Type", "application/json");
                post.setEntity(entity);
                HttpResponse response = client.execute(post);
                StatusLine status = response.getStatusLine();
                if (status.getStatusCode() >= 300)
                    throw new RuntimeException(status.toString());
            }
            public void stop() throws Exception {}
        });
    }
    @Path("/")
    public class Root {
        @GET
        public Object get() { return null; }
    }
}
```

### PR DESCRIPTION
**Pull request by reines**
Fixes #403

### CODE REVIEW

**Comment by charbonnier666** [comment]
sorry how can I use in project or in a single response ?

**Comment by arteam** [comment]
```java
JerseyClientConfiguration configuration = new JerseyClientConfiguration();
configuration.setChunkedEncodingEnabled(false);
Client jersey = new JerseyClientBuilder(environment)
                .using(configuration)
                .build("jersey-test");
```

**Comment by charbonnier666** [comment]
@arteam Thanks, but where I must put ? (I fork dropwizard-example) ...and I don't find JerseyClientConfiguration in my project... mm

**Comment by arteam** [comment]
`dropwizard-example` doesn't have any integration with `dropwizard-client`. If you have question regarding using the API, please post them to the `dropwizard-user` mailing list.

**Pull request merged**
