### PR TITLE
Remove jUnit 4.x support

### PR DESCRIPTION
**Pull request by rhowe**
Raised more as a "we could" rather than necessarily a "we should".

Is it worth moving it to a new module rather than outright removing it? `dropwizard-testing-junit4`?

### CODE REVIEW

**Comment by zUniQueX** [comment]
> Is it worth moving it to a new module rather than outright removing it? `dropwizard-testing-junit4`?

I've already thought about that. This could be problematic, as it would depend on the `io.dropwizard.testing.common` package. If the jUnit 4.x module would depend on the jUnit 5.x one, I think this would be surprising.

However, we could split the package into three modules and extract the common classes to a seperate one.

**Comment by rhowe** [comment]
> > Is it worth moving it to a new module rather than outright removing it? `dropwizard-testing-junit4`?
> 
> I've already thought about that. This could be problematic, as it would depend on the `io.dropwizard.testing.common` package. If the jUnit 4.x module would depend on the jUnit 5.x one, I think this would be surprising.
> 
> However, we could split the package into three modules and extract the common classes to a seperate one.

I think that with the appropriate marketing, it could be fine - `dropwizard-testing-junit4-compat` or something, at least a name that hinted it was an addon to dropwizard-testing whose days were numbered.

**Comment by rhowe** [comment]
An alternative could be to mark the jUnit 4 support classes as deprecated, although that doesn't remove it from the classpath (yes I know you can exclude dependencies in your build tool, but I don't think that kind of behaviour should be encouraged)

**Comment by zUniQueX** [comment]
> An alternative could be to mark the jUnit 4 support classes as deprecated, although that doesn't remove it from the classpath (yes I know you can exclude dependencies in your build tool, but I don't think that kind of behaviour should be encouraged)

This wouldn't give us any advantage IMO. If we won't remove the jUnit 4.x classes, we would have to provide support for it.

**Review by joschi — APPROVED** [review]
I've extracted the JUnit 4.x classes into a separate module: https://github.com/dropwizard/dropwizard-testing-junit4

With this in mind, I'm okay with removing JUnit 4.x support in the `release/3.0.x` branch.

@rhowe Could you please add a note to use https://github.com/dropwizard/dropwizard-testing-junit4 to the Dropwizard 3.0.x upgrade notes?
https://github.com/rhowe/dropwizard/blob/remove-junit4/docs/source/manual/upgrade-notes/upgrade-notes-3_0_x.rst

**Comment by rhowe** [comment]
> @rhowe Could you please add a note to use https://github.com/dropwizard/dropwizard-testing-junit4 to the Dropwizard 3.0.x upgrade notes? https://github.com/rhowe/dropwizard/blob/remove-junit4/docs/source/manual/upgrade-notes/upgrade-notes-3_0_x.rst

Done, although do check my wording

**Comment by zUniQueX** [comment]
Looks good :+1: 

Just one small thing: Markdown uses an other link notation than RST. So your link in the upgrade document is not correctly displayed.

**Comment by rhowe** [comment]
> Just one small thing: Markdown uses an other link notation than RST. So your link in the upgrade document is not correctly displayed.

So it does. Fixed & rebased.

**Pull request merged**
