### PR TITLE
Add CommandRunner to dropwizard-testing

### PR DESCRIPTION
**Pull request by oillio**
I needed a way to run commands during integration testing.

This PR adds a CommandRunner that supports running Commands against a provided Application and configuration.  I also refactored DropwizardTestSupport so that it and CommandRunner can share code.

### CODE REVIEW

**Comment by arteam** [comment]
Thanks for you pull request.

I'm curious, what's wrong with running commands through
````java
DropwizardAppRule<HelloWorldConfiguration> rule;
// ...
rule.getApplication().run("command", "parameter");
````

If you want to write an integration test for a command without starting an HTTP server, you can just create an application class by hand.

Do your commands have some state you want to inspect? This seems like a bad practice for me.

**Comment by oillio** [comment]
Yep, the goal is to run the Command under test without also running the ServerCommand.  I wanted a way to run a Command as close as possible to how it will be run in production.

It is common for me to have setup and configuration occurring in my Application initialize method which is required by my Commands.  It seems wasteful to need to duplicate this initialization, or do other backflips, so that I can create an Application class for command testing.

**Comment by arteam** [comment]
I see your case. I will try to look more closely on this PR this week.

**Comment by arteam** [comment]
I gave it more thought and came to the conclusion that the problem is not worth to solve. Al least it's not worth of creation of another abstraction level. Most commands are are simple and stateless, so they can be tested by invoking the `run` method of `Application`. I think, it's enough for most users.
If people will ask for this functionality, we can return to this PR.

Sorry.

**Pull request closed without merging**
