### PR TITLE
First stab on dropwizard-benchmarks

### PR DESCRIPTION
**Pull request by arteam**
Add benchmarks for [Duration](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-util/src/main/java/io/dropwizard/util/Duration.java) and [Size](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-util/src/main/java/io/dropwizard/util/Size.java)

The benchmarks measure an average time to parse a string to Duration and Size representations.

### CODE REVIEW

**Comment by jplock** [comment]
This looks good to me.  @carlo-rtr did you want the benchmarks to focus more on benchmarking the entire system (Jetty, Jersey, etc.), or is this level of granularity ok?

**Comment by carlo-rtr** [comment]
I was thinking more macro, like the empower benchmarks. I've updated the issue: https://github.com/dropwizard/dropwizard/issues/963

With that said, it seems like this would be useful too. I have never used this before, so I'm going to read up then opine.

**Comment by arteam** [comment]
My 2 cents:

* The situation with micro-benchmarks is a very similar to unit testing. There is a little profit from one lone benchmark, but when the all code is covered by benchmarks, it's far easier to find the root of a perfomance problem early. When a developer checks-in the new code, we can run micro-benchmarks and check regression. If there is any, it's a sign of a possible performance problem.
* It's a tool for the maintainers to argue about perfomance with numbers. For example, if a maintainer thinks that a pull request decreases performance, he can consolidate his opinion with numbers.
* I don't know where it will lead us, but it's a tool that can improve our awareness in making decisions. More data is better.

**Comment by jplock** [comment]
I think this is a good first step.  I'll merge it.

**Comment by carlo-rtr** [comment]
Do you think we should have an abstract class with the main method? The only thing changing is the name, we could have an abstract method for getBenchMarkName()

**Comment by ryankennedy** [comment]
This is really cool. Any reason not to shade the final JAR and make the Main-Class be `org.openjdk.jmh.Main`? I just pulled these changes down and tried to run them but the resulting JAR doesn't have a Main-Class attribute in the manifest and even specifying the `DurationBenchmark` class results in a `java.lang.NoClassDefFoundError: io/dropwizard/util/Duration`.

The [instructions for generating a project](http://openjdk.java.net/projects/code-tools/jmh/) using `mvn archetype:generate` generate a POM with shading and the Main-Class set up like I mentioned above. I'd be happy to go in and make the changes, but I first wanted to make sure @arteam hadn't skipped those for good reason.

**Pull request merged**
