### PR TITLE
Configurable prudent mode

### PR DESCRIPTION
**Pull request by genz10**
Issue refference : https://github.com/dropwizard/dropwizard/issues/2142

Users will able to enable prudent mode in JSON config file.

### CODE REVIEW

**Comment by genz10** [comment]
I've missed some important part behind prudent mode, such as 

`In prudent mode, file compression is not supported nor allowed. (We can't have one JVM writing to a file while another JVM is compressing it.)`

In my opinion, it will trigger another problem such as archiving and massive log size (CMIIW). Reason behind I want to enable prudent mode was I have multiple JVM writing on the same log file.

Do anyone here have more simple and elegant solution ? 

Thanks!

**Comment by mattnelson** [comment]
> Do anyone here have more simple and elegant solution ?

I would try to avoid having multiple process write to the same file. It would likely be easier to join those files together after the fact. But if you really must have this feature, then I would recommend using logrotate for compression/rotation instead of logback's built in implementation.

**Comment by isaki-x** [comment]
I agree that using logrotate for the compression is way better (and if this PR goes through, it should probably throw an exception or something if prudent is enabled with logback's compression enabled). Another option would be use a syslog appender and no need to deal with prudent at all.

**Comment by genz10** [comment]
Yeah I think these trade off are not balance, once someone enable prudent mode (if this PR goes through) there's possibility they will suffer another problem, i'll also consider to find other solution instead of enabling prudent mode.

Should we close this PR or continue goes through ?

**Comment by arteam** [comment]
Okay, let's put this PR on hold. We can continue, if there is more interest from the community and clear how to tackle the rotation issue.

**Comment by joschi** [comment]
The PR seems to be stale and hasn't seen any activity in almost 2 years.
I'm closing it for now until someone picks up the work and addresses the remaining issues.

**Pull request closed without merging**
