### PR TITLE
Mark constructors of abstract classes protected

### PR DESCRIPTION
**Pull request by rhowe**
###### Problem:

Sonar found 6 cases where constructors of abstract classes are declared `public`:

- dropwizard-configuration's [BaseConfigurationFactory](https://sonarcloud.io/project/issues?id=dropwizard_dropwizard&issues=AXUXdISKpBosHuY9-Pwm&open=AXUXdISKpBosHuY9-Pwm)
- dropwizard-configuration `ConfigurationException` [1](https://sonarcloud.io/project/issues?id=dropwizard_dropwizard&issues=AXUXdIS1pBosHuY9-Pwo&open=AXUXdIS1pBosHuY9-Pwo), [2](https://sonarcloud.io/project/issues?id=dropwizard_dropwizard&issues=AXUXdIS1pBosHuY9-Pwp&open=AXUXdIS1pBosHuY9-Pwp)
- dropwizard-jersey [ErrorEntityWriter](https://sonarcloud.io/project/issues?id=dropwizard_dropwizard&issues=AXUXdIFVpBosHuY9-Ps8&open=AXUXdIFVpBosHuY9-Ps8), [LoggingExceptionMapper](https://sonarcloud.io/project/issues?id=dropwizard_dropwizard&issues=AXUXdIFJpBosHuY9-Ps6&open=AXUXdIFJpBosHuY9-Ps6)
- dropwizard-migrations [CloseableLiquibase](https://sonarcloud.io/project/issues?id=dropwizard_dropwizard&issues=AXUXdIwtpBosHuY9-P8H&open=AXUXdIwtpBosHuY9-P8H)

###### Solution:
Make these constructors protected. You can't construct an abstract class directly.

###### Result:
I think no change.

### CODE REVIEW

**Comment by joschi** [comment]
@rhowe Thanks for your contribution!

Unfortunately these are breaking changes in public APIs, so we won't be able to apply them until Dropwizard 3.0.0 if at all.

**Review by joschi — DISMISSED** [review]
@rhowe Thanks for your contribution!

Unfortunately these are breaking changes in public APIs, so we won't be able to apply them until Dropwizard 3.0.0 if at all.

See also: https://wiki.eclipse.org/Evolving_Java-based_APIs_2

**Comment by rhowe** [comment]
> @rhowe Thanks for your contribution!
> 
> Unfortunately these are breaking changes in public APIs, so we won't be able to apply them until Dropwizard 3.0.0 if at all.
> 
> See also: https://wiki.eclipse.org/Evolving_Java-based_APIs_2

I don't see a problem in not applying this change at all tbh, since I doubt the current state of affairs is really a problem, but is it really a breaking change?

The classes are abstract, which means nothing can call the constructor directly except either themselves or a subclass. Doesn't that mean that declaring the constructor public is equivalent to declaring it protected?

**Comment by zUniQueX** [comment]
I think we can bring this to 3.0.0, so this can be merged to `release/3.0.x` IMO.

**Review by zUniQueX — APPROVED** [review]

**Pull request merged**
