### PR TITLE
Generalize DropwizardAppRule for other test frameworks

### PR DESCRIPTION
**Pull request by csabapalfi**
Hi,

I was looking at starting/stopping a Dropwizard app in Cucumber tests and DropwizardAppRule has all the functionality I need but obviously it doesn't expose startIfRequired and stop methods.

I'd happy to extract a DropWizardAppTestSupport class from DropwizardAppRule and make the DropwizardAppRule depend on that and contribute the code if there's any interest.

What do you think?

Thanks,
Csaba

### CODE REVIEW

**Comment by joschi** [comment]
If someone steps up to update the PR to apply cleanly to current master, we'll happily merge it. (@ddunwoody, @hslater-okta)

**Comment by ddunwoody** [comment]
I'll take a look this week.  It's my last week on the project that uses this, so it would be a nice feeling to get it merged in.

**Comment by csabapalfi** [comment]
Sorry about the delay. 

Re-done the change on the latest master (as it diverged a lot).

2 tests were failing locally when run with all others (but passing in isolation). That still needs fixing.

**Comment by csabapalfi** [comment]
The patch keeps everything backwards compatible. Is that required? If not then the code can be a bit simpler in some cases.

**Comment by csabapalfi** [comment]
Found the cause of the test failures. One of the test was not cleaning up after itself properly and left an extra system property confusing the tests run afterwards.

**Comment by csabapalfi** [comment]
Just spotted that the same test problem is already on master. Introduced by https://github.com/dropwizard/dropwizard/commit/9848d9b5275dff6255b1aa255b8075638a1cdb20

 If you merge my PR and that'll fix the tests on master, too.

**Comment by joschi** [comment]
Great! Thanks for the PR.

**Comment by ddunwoody** [comment]
Thanks everyone.  I was saving this for work in the morning, but looks like you beat me to it!

**Pull request merged**
