### PR TITLE
Integrate with Code Climate

### PR DESCRIPTION
**Pull request by ryankennedy**
Code Climate recently added the ability to run [Checkstyle](https://github.com/checkstyle/checkstyle) and [PMD](http://pmd.github.io/) against projects. This can be done against pull requests, allowing the system to quickly flag style and static analysis issues in pull requests before we even start reviewing.

I noticed @arteam already has two CLs ( #1065 and #1371 ) where he's gone back and done this manually and retroactively. If we'd had Code Climate in place the person submitting the code would have been notified to fix the issue before the PR would have been accepted.

I haven't specified a custom Checkstyle config (here's [an example](https://github.com/mrb/kafka/blob/trunk/.codeclimate.yml) for the Kafka project). We'd probably want to settle on a style and check it in prior to or as part of this commit. If there's no objections to this, I can get it submitted and we can get the webhook integration working.

@dropwizard/committers

### CODE REVIEW

**Comment by joschi** [comment]
@ryankennedy Good idea. Thanks!

Is there anything we have to change in the `.codeclimate.yml` file or could we just merge this PR?

Do you happen to have any reference to the PMD and Checkstyle features of Code Climate? I fail to find anything beyond https://github.com/sivakumar-kailasam/codeclimate-pmd.

**Comment by mrb** [comment]
@joschi Hey there! Sorry about that - I just made the documentation public https://docs.codeclimate.com/v1.0/docs/pmd and https://docs.codeclimate.com/v1.0/docs/checkstyle - I'd be happy to answer any other questions you have!

**Comment by mrb** [comment]
@joschi @ryankennedy I would recommend tweaking the configurations for these engines before we integrate the PR support, would be happy to help with that!

**Comment by ryankennedy** [comment]
@joschi I was just going to say what @mrb said. We should customize the checkstyle configuration before the PR integration, otherwise subsequent pull requests may get hit with requests to make style changes that we don't actually want them to make.

@arteam, what config did you use the last few times you ran checkstyle?

**Comment by ryankennedy** [comment]
Here's the results with the default pmd/checkstyle configurations. Checkstyle has [some XML configs](https://github.com/checkstyle/checkstyle/tree/master/src/main/resources) we might be able to repurpose, but neither of them looks to fit exactly what we're doing today. If anyone has a checkstyle.xml that they've been using that they feel matches the style we want to enforce going forward, let me know.

The pmd feedback largely boils down to "Do not hard code the IP address" (these all appear to be tests) and "These nested if statements could be combined".

**Comment by ryankennedy** [comment]
The [Kafka checkstyle config](https://github.com/mrb/kafka/blob/trunk/checkstyle/checkstyle.xml) runs with only 48 reported errors (28 of which are indentation). Shall we start there?

**Comment by ryankennedy** [comment]
Code Climate shows a checkstyle [clean bill of health](https://codeclimate.com/github/ryankennedy/dropwizard/issues) after the last two commits. There's just some PMD stuff that needs sorting, mostly complaints about embedding IP addresses in our tests.

I'd like to get this merged so we can turn on Code Climate's pull request integration as a gatekeeper to prevent any further code that doesn't conform to the style guide. Any objections from @dropwizard/committers?

**Comment by joschi** [comment]
LGTM. 👍 
Thanks for the effort, Ryan!

**Comment by mrb** [comment]
@ryankennedy @joschi Awesome!! Let me know how I can help if anything comes up.

**Pull request merged**
