### PR TITLE
Expose the ObjectMapper and Environment from the FakeApplication

### PR DESCRIPTION
**Pull request by jplock**
Fixes https://github.com/dropwizard/dropwizard/issues/1393

### CODE REVIEW

**Comment by evnm** [comment]
To minimize the change, we could simply expose `getEnvironment()`. Consumers could then access the `ObjectMapper` via `Environment.getObjectMapper()`.

Not sure if we care, though. LGTM!

**Comment by jplock** [comment]
@evnm I thought about that, but then I saw that `DropwizardTestSupport` exposes them both this way anyway so I figured it'd be ok.

**Comment by evnm** [comment]
Yep, seems consistent to me.

**Comment by arteam** [comment]
I think that's fine. Users will have more control over the testing environment.

**Comment by arteam** [comment]
Thanks, @jplock and @evnm!

**Pull request merged**
