### PR TITLE
Merge Release/1.0.x into master

### PR DESCRIPTION
**Pull request by jplock**
`master` was missing https://github.com/dropwizard/dropwizard/pull/1664

### CODE REVIEW

**Comment by jplock** [comment]
@nickbabcock Since commits were cherry-picked, its hard to say what was in here and what may have been missed.

**Comment by nickbabcock** [comment]
Hmm, my git-fu may be failing me but I think #1664 is the only thing that needs to be applied to master:

```
git log v1.0.1 --merges --since='2016-07-26'
```

yields only the mentioned pull request and

```
git log --grep 'cherry pick' --invert-grep  v1.0.1 ^master --cherry --before=$(date -I -d "yesterday")
```
yields a the mentioned pull request and a false positive.

**Comment by arteam** [comment]
#1664 was originally merged to the 1.0.x branch and I applied it to master in e34310b2

**Comment by jplock** [comment]
Strange.  I'm fine closing this out.  I was just curious if we had missed anything.

**Pull request closed without merging**
