### PR TITLE
Support Dropwizard applications without logback

### PR DESCRIPTION
**Pull request by arteam**
This is a prototype for splitting the tight integration between Dropwizard and Logback. This feature was requested several times (See #1367). The idea is too provide users the ability to exclude Logback from Dropwizard and replace it with an external logging solution, if they really want to. The main work of this PR is too initialize the Logback infrastructure lazily, so the user can swap it to an external logging mechanism in the config file.

With this change users can swap logback to other logging implementation like that:
```xml
 <dependencies>

        <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-core</artifactId>
            <version>1.1.0-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-classic</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-access</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>log4j-over-slf4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.17</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.7.21</version>
        </dependency>

    </dependencies>
``` 

```yml
server:
  type: simple
  applicationContextPath: /application
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
  requestLog:
    type: external
logging:
  type: external
```

```java
public class ExampleApplication extends Application<ExampleConfiguration> {

    @Override
    protected void bootstrapLogging() {
    }
}
```

### CODE REVIEW

**Comment by arteam** [comment]
@dropwizard/committers Could you please review? This should be ready to merge. I tested it locally and it works with custom logging solutions. Would be nice to polish it and adopt to the framework.

**Comment by jplock** [comment]
@arteam mind updating the release notes too?

**Comment by arteam** [comment]
Will do. It probably make sense to mention in the docs how to switch to an external logging.

**Comment by jplock** [comment]
@arteam this is just pending documentation, correct?

**Comment by arteam** [comment]
Correct, I need to get my hands on it. Will do today.

**Comment by arteam** [comment]
I've added docs about disabling Logback to the core guide.

**Comment by jplock** [comment]
Thanks!

**Comment by vybs** [comment]
@arteam  is there a slated release for this anytime soon, i,e 1.2.0 ?

**Comment by arteam** [comment]
We don't have an ETA for 1.2.0, unfortunately. You can use snapshots builds for the time being, if you want to test this feature.

We could cut a release candidate for 1.2.0, but we need to discuss this among the maintainers.

**Comment by zackehh** [comment]
@arteam is there a repository holding the latest snapshot of Dropwizard, or do we have to build it ourselves? 

(also, thank you greatly for this PR, works perfectly)

**Comment by arteam** [comment]
I think you can use the Nexus snapshot repository, our snapshots should be there:

```
<repository>
  <id>sonatype-nexus-snapshots</id>
  <name>Sonatype Nexus Snapshots</name>
  <url>http://oss.sonatype.org/content/repositories/snapshots</url>
</repository>
```

**Comment by jsauvain** [comment]
I just tried to use this feature with 1.2.0-SNAPSHOT.

io.dropwizard.jackson.LogbackModule imports the Level class from Logback. Could you please fix that?

**Comment by arteam** [comment]
Thanks for pointing this out. It seems the configuration of the Jackson's ObjectMapper in Dropwizard is still dependent on Logback. I will take a look on it.

**Pull request merged**
