### PR TITLE
Update h2 to 2.1.210

### PR DESCRIPTION
**Pull request by zUniQueX**
Check in a new test db file for h2 v2 and update the dependency.

Closes https://github.com/dropwizard/dropwizard/pull/4631
Closes https://github.com/dropwizard/dropwizard/pull/4865

### CODE REVIEW

**Comment by joschi** [comment]
The branch is currently failing on Windows: https://ci.appveyor.com/project/dropwizard/dropwizard/builds/42870811
```text
org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/projects/dropwizard/dropwizard-migrations/target/test-classes/test-db" [50000-210]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:216)
	at org.h2.message.DbException.convert(DbException.java:414)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59
```

It looks like something in the path handling of H2 changed in an incompatible way.

**Comment by zUniQueX** [comment]
According to [this StackOverflow thread](https://stackoverflow.com/questions/43972777/exception-in-thread-main-java-nio-file-invalidpathexception-illegal-char) this is an error in the `URI.toPath()` method.

**Comment by zUniQueX** [comment]
@joschi I've now fixed the build on Windows. Should we additionally backport this to the 2.0.x branch?

**Comment by joschi** [comment]
> @joschi I've now fixed the build on Windows. Should we additionally backport this to the 2.0.x branch?

@zUniQueX No, I think we're fine. Dropwizard 2.0.x will be maintenance only once Dropwizard 2.1.x has been released and H2 is only used in tests anyway.

**Review by joschi — APPROVED** [review]
LGTM, thanks! ❤️

**Pull request merged**
