### PR TITLE
Update jackson from v2.7.6 -> v2.7.8

### PR DESCRIPTION
**Pull request by jmoney8080**
Fixes: https://github.com/FasterXML/jackson-databind/issues/1383

### CODE REVIEW

**Comment by jplock** [comment]
Maybe we should target this PR against the `release-1.0.x` branch because #1749 is going to update `master` to Jackson 2.8

**Comment by jplock** [comment]
Changing the base within github brings in too many other commits.  We'll need a fresh PR unfortunately.

**Comment by joschi** [comment]
@jplock I think it would work if @jmoney8080 rebased his branch on `release/1.0.x` instead of `master` and force-pushed it to GitHub.

**Comment by jmoney8080** [comment]
New PR https://github.com/dropwizard/dropwizard/pull/1755
closing this PR out.

**Pull request closed without merging**
