### PR TITLE
Remove Jersey dependency from dropwizard-core.

### PR DESCRIPTION
**Pull request by ghenkes**
Decouple dropwizard-core from Jersey by providing a JerseyServletContainer in dropwizard-jersey.
This would allow consumers to implement their own dropwizard-jersey using Jersey 1.

See: https://github.com/dropwizard/dropwizard/issues/1038

### CODE REVIEW

**Comment by arteam** [comment]
Seems harmless enough. @joshi, what do you think?

**Comment by carlo-rtr** [comment]
Seems fine to me

**Comment by ghenkes** [comment]
@arteam @carlo-rtr I made a small change to JerseyServletContainer to take in a DropwizardResourceConfig rather than a ResourceConfig. I also pulled in the latest changes from dropwizard into my fork, that's why you'll see those 2 merge commits.

**Comment by arteam** [comment]
Applied to master with tweaks in 2a08d3

**Pull request closed without merging**
